namespace DBCode {
   public sealed partial class MainForm : Form {
      public MainForm() {
         mForm = this;
         Opacity = 0;
         InitializeUI();
         mThisWindow = Handle;
         int wantedWidth = MinimumMainBottomWidth() + 20;
         if (mUiState.mFirstLaunch) {
            mUiState.FormBounds = new Rectangle(new Point(1, 1), new Size(wantedWidth, 300));
            mForm.Bounds = mUiState.FormBounds;
            EnsureWindowFitsMonitor(this);
            CenterFormOnMonitor(this);
            mUiState.FormBounds = mForm.Bounds;
            mUiState.mFirstLaunch = false;
         }
         MinimumSize = new Size(wantedWidth, 150);
         Assembly assembly = Assembly.GetExecutingAssembly();
         FileVersionInfo? fileVersionInfo = FileVersionInfo.GetVersionInfo(assembly.Location);
         if (fileVersionInfo == null)
            mVersionString = "0.0.0.0";
         else {
            if (fileVersionInfo.FileVersion == null)
               mVersionString = "0.0.0.0";
            else {
               mVersionString = fileVersionInfo.FileVersion;
               if (mVersionString == null)
                  mVersionString = "0.0.0.0";
            }
         }
         mVersionLabel?.Text = "v: " + mVersionString;
         mCurrentViewMode = ViewMode.Features;
         mIsTargetingEnabled = false;
         mTargetWindowName = string.Empty;
         mPreMinimalText = Text;
         mPreMinimalControlBox = ControlBox;
         TargetListManager.EnsureDataFiles();
      }

      private static void MakeNews() {
         ThrowIfNull(mCurrentTheme, nameof(mCurrentTheme));
         mMenuStrip = new MenuStrip();
         mContextMenuStrip = new ContextMenuStrip();
         mTargetingMenuItem = new ToolStripMenuItem();
         mVisibilityMenuItem = new ToolStripMenuItem();
         mModeMenuItem = new ToolStripMenuItem();
         mLanguageMenuItem = new ToolStripMenuItem();
         mOptionsMenuItem = new ToolStripMenuItem();
         mThemeMenuItem = new ToolStripMenuItem();
         mThemeDesignTSMI = new ToolStripMenuItem();
         mThemePickTSMI = new ToolStripMenuItem();
         mThemeEditTSMI = new ToolStripMenuItem();
         mThemeEditPickTSMI = new ToolStripMenuItem();
         mThemeEditCurrentTSMI = new ToolStripMenuItem();
         mHelpMenuItem = new ToolStripMenuItem();
         mTargetedTSMI = new ToolStripMenuItem();
         mRetargetTSMI = new ToolStripMenuItem();
         mTransparentTSMI = new ToolStripMenuItem();
         mThirtyTSMI = new ToolStripMenuItem();
         mFiftyTSMI = new ToolStripMenuItem();
         mSeventyFiveTSMI = new ToolStripMenuItem();
         mOpaqueTSMI = new ToolStripMenuItem();
         mMinimalTSMI = new ToolStripMenuItem();
         mFeaturesTSMI = new ToolStripMenuItem();
         mPlainTextTSMI = new ToolStripMenuItem();
         mCSharpTSMI = new ToolStripMenuItem();
         mCTSMI = new ToolStripMenuItem();
         mCppTSMI = new ToolStripMenuItem();
         mBasicTSMI = new ToolStripMenuItem();
         mFSharpTSMI = new ToolStripMenuItem();
         mHtmlTSMI = new ToolStripMenuItem();
         mCssTSMI = new ToolStripMenuItem();
         mXmlTSMI = new ToolStripMenuItem();
         mJsonTSMI = new ToolStripMenuItem();
         mPowerShellTSMI = new ToolStripMenuItem();
         mBatchTSMI = new ToolStripMenuItem();
         mSqlTSMI = new ToolStripMenuItem();
         mMarkdownTSMI = new ToolStripMenuItem();
         mPythonTSMI = new ToolStripMenuItem();
         mCurrentThemeIsTSMI = new ToolStripMenuItem();
         mContextUndoTSMI = new ToolStripMenuItem();
         mContextRedoTSMI = new ToolStripMenuItem();
         mContextCopyAllTSMI = new ToolStripMenuItem();
         mContextCopyTSMI = new ToolStripMenuItem();
         mContextCutTSMI = new ToolStripMenuItem();
         mContextDeleteTSMI = new ToolStripMenuItem();
         mContextPasteTSMI = new ToolStripMenuItem();
         mContextSelectAllTSMI = new ToolStripMenuItem();
         mContextSelectNoneTSMI = new ToolStripMenuItem();
         mContextFindTSMI = new ToolStripMenuItem();
         mContextFindNextTSMI = new ToolStripMenuItem();
         mContextFindPreviousTSMI = new ToolStripMenuItem();
         mContextReplaceTSMI = new ToolStripMenuItem();
         mContextGoToTSMI = new ToolStripMenuItem();
         mEditMenuItem = new ToolStripMenuItem();
         mEditUndoTSMI = new ToolStripMenuItem();
         mEditRedoTSMI = new ToolStripMenuItem();
         mEditCutTSMI = new ToolStripMenuItem();
         mEditDeleteTSMI = new ToolStripMenuItem();
         mEditPasteTSMI = new ToolStripMenuItem();
         mEditSelectAllTSMI = new ToolStripMenuItem();
         mEditSelectNoneTSMI = new ToolStripMenuItem();
         mEditTrimToBeginningTSMI = new ToolStripMenuItem();
         mEditTrimToEndTSMI = new ToolStripMenuItem();
         mEditCopyTSMI = new ToolStripMenuItem();
         mEditCopyAllTSMI = new ToolStripMenuItem();
         mEditCopyToBeginningTSMI = new ToolStripMenuItem();
         mEditCopyToEndTSMI = new ToolStripMenuItem();
         mEditFindTSMI = new ToolStripMenuItem();
         mEditFindNextTSMI = new ToolStripMenuItem();
         mEditFindPreviousTSMI = new ToolStripMenuItem();
         mEditReplaceTSMI = new ToolStripMenuItem();
         mEditGoToTSMI = new ToolStripMenuItem();
         mEditWordWrapTSMI = new ToolStripMenuItem();
         mCSharpCommentAddDoubleTSMI = new ToolStripMenuItem();
         mCSharpAddNotImplementedTSMI = new ToolStripMenuItem();
         mCSharpCommentAddTripleTSMI = new ToolStripMenuItem();
         mCPlusPlusCommentTSMI = new ToolStripMenuItem();
         mCSharpExpressionBodiedMethodTSMI = new ToolStripMenuItem();
         mCSharpCommentOutTSMI = new ToolStripMenuItem();
         mCSharpCommentRemoveTSMI = new ToolStripMenuItem();
         mCSharpReverseEqualityTSMI = new ToolStripMenuItem();
         mConvertVBToCSharpCommentTSMI = new ToolStripMenuItem();
         mCodingTSMI = new ToolStripMenuItem();
         mCodingCFamilyTSMI = new ToolStripMenuItem();
         mCodingBasicTSMI = new ToolStripMenuItem();
         mBasicAddSingleQuoteTSMI = new ToolStripMenuItem();
         mBasicConvertCSharpToVBCommentTSMI = new ToolStripMenuItem();
         mBasicReverseEqualityTSMI = new ToolStripMenuItem();
         mBasicRemoveLineContinuationTSMI = new ToolStripMenuItem();
         mBasicConvertBooleansTSMI = new ToolStripMenuItem();
         mBasicConvertNullNothingTSMI = new ToolStripMenuItem();
         mBasicConvertLogicalOperatorsTSMI = new ToolStripMenuItem();
         mCodingFSharpTSMI = new ToolStripMenuItem();
         mFSharpBlockCommentTSMI = new ToolStripMenuItem();
         mFSharpAddCommentTSMI = new ToolStripMenuItem();
         mFSharpAddMutableTSMI = new ToolStripMenuItem();
         mFSharpAddIgnoreTSMI = new ToolStripMenuItem();
         mFSharpConvertNullNoneTSMI = new ToolStripMenuItem();
         mCodingHTMLTSMI = new ToolStripMenuItem();
         mHTMLCommentTSMI = new ToolStripMenuItem();
         mHTMLBoldTSMI = new ToolStripMenuItem();
         mHTMLItalicTSMI = new ToolStripMenuItem();
         mHTMLUnderlineTSMI = new ToolStripMenuItem();
         mHTMLStrikethroughTSMI = new ToolStripMenuItem();
         mHTMLBigTSMI = new ToolStripMenuItem();
         mHTMLBigBigTSMI = new ToolStripMenuItem();
         mHTMLSmallTSMI = new ToolStripMenuItem();
         mHTMLSmallSmallTSMI = new ToolStripMenuItem();
         mHTMLMarkTSMI = new ToolStripMenuItem();
         mHTMLSuperscriptTSMI = new ToolStripMenuItem();
         mHTMLSubscriptTSMI = new ToolStripMenuItem();
         mHTMLCodeTSMI = new ToolStripMenuItem();
         mHTMLPreformattedTSMI = new ToolStripMenuItem();
         mHTMLColorizeTSMI = new ToolStripMenuItem();
         mCodingCSSTSMI = new ToolStripMenuItem();
         mCSSBlockCommentTSMI = new ToolStripMenuItem();
         mCSSCommentRemoveTSMI = new ToolStripMenuItem();
         mCSSToggleImportantTSMI = new ToolStripMenuItem();
         mCSSConvertColorFormatTSMI = new ToolStripMenuItem();
         mCodingXMLTSMI = new ToolStripMenuItem();
         mXMLCommentTSMI = new ToolStripMenuItem();
         mXMLRemoveCommentTSMI = new ToolStripMenuItem();
         mXMLEscapeEntitiesTSMI = new ToolStripMenuItem();
         mXMLWrapCDataTSMI = new ToolStripMenuItem();
         mXMLToggleSelfCloseTSMI = new ToolStripMenuItem();
         mCodingJSONTSMI = new ToolStripMenuItem();
         mJSONAddCommentTSMI = new ToolStripMenuItem();
         mJSONBlockCommentTSMI = new ToolStripMenuItem();
         mJSONRemoveCommentTSMI = new ToolStripMenuItem();
         mJSONToggleQuotesTSMI = new ToolStripMenuItem();
         mJSONEscapeStringTSMI = new ToolStripMenuItem();
         mJSONRemoveTrailingCommasTSMI = new ToolStripMenuItem();
         mCodingPowerShellTSMI = new ToolStripMenuItem();
         mPowerShellAddCommentTSMI = new ToolStripMenuItem();
         mPowerShellBlockCommentTSMI = new ToolStripMenuItem();
         mPowerShellRemoveCommentTSMI = new ToolStripMenuItem();
         mPowerShellToggleBooleanTSMI = new ToolStripMenuItem();
         mPowerShellToggleQuotesTSMI = new ToolStripMenuItem();
         mCodingBatchTSMI = new ToolStripMenuItem();
         mBatchAddCommentTSMI = new ToolStripMenuItem();
         mBatchAddColonCommentTSMI = new ToolStripMenuItem();
         mBatchRemoveCommentTSMI = new ToolStripMenuItem();
         mBatchToggleCommentStyleTSMI = new ToolStripMenuItem();
         mCodingSQLTSMI = new ToolStripMenuItem();
         mSQLAddCommentTSMI = new ToolStripMenuItem();
         mSQLBlockCommentTSMI = new ToolStripMenuItem();
         mSQLRemoveCommentTSMI = new ToolStripMenuItem();
         mSQLToggleNullCheckTSMI = new ToolStripMenuItem();
         mSQLToggleBooleanTSMI = new ToolStripMenuItem();
         mCodingMarkdownTSMI = new ToolStripMenuItem();
         mMarkdownCommentTSMI = new ToolStripMenuItem();
         mMarkdownBoldTSMI = new ToolStripMenuItem();
         mMarkdownItalicTSMI = new ToolStripMenuItem();
         mMarkdownBoldItalicTSMI = new ToolStripMenuItem();
         mMarkdownStrikethroughTSMI = new ToolStripMenuItem();
         mMarkdownCodeTSMI = new ToolStripMenuItem();
         mMarkdownCodeBlockTSMI = new ToolStripMenuItem();
         mCodingPythonTSMI = new ToolStripMenuItem();
         mPythonAddCommentTSMI = new ToolStripMenuItem();
         mPythonBlockCommentTSMI = new ToolStripMenuItem();
         mPythonRemoveCommentTSMI = new ToolStripMenuItem();
         mPythonToggleBooleanTSMI = new ToolStripMenuItem();
         mPythonConvertNullNoneTSMI = new ToolStripMenuItem();
         mCSharpWrapTSMI = new ToolStripMenuItem();
         mScrollableMainPanel = new ScrollablePanel() {
            Name = "mainPanel",
            AutoScroll = true,
            TabIndex = mTabIndex++,
            BackColor = mCurrentTheme.mInterfaceColors[(int)ColorSwatchUsage.InterfaceBackground]
         };
         mRichTextBox = new RichTextBox();
         mSendAllButton = new Button();
         mPasteSelectedButton = new Button();
         mGetAllButton = new Button();
         mGetSelectedButton = new Button();
         mTargetingLabel = new Label();
         mVersionLabel = new Label();
         mRevertButton = new Button();
         mMainBottomPanel = new BottomPanel(mCurrentTheme, "E&xit");
      }

      private void InitializeUI() {
         mUiState = new UiState();
         mUiState.Read();
         mUsePCRE = mUiState.mUsePCRE;
         ThemeRegistry.Initialize(); // must precede MakeNews so mCurrentTheme and mThemes are ready
         MakeNews();
         ValidateAllFields();
         LoadEmbeddedIcons();
         // --- shortcut keys ---
         mThemeEditPickTSMI.ShortcutKeys = Keys.Control | Keys.Shift | Keys.E;
         mThemeEditCurrentTSMI.ShortcutKeys = Keys.Control | Keys.Shift | Keys.C;
         mThemeDesignTSMI.ShortcutKeys = Keys.Control | Keys.Shift | Keys.D;
         mHelpMenuItem.ShortcutKeys = Keys.F1;
         mEditUndoTSMI.ShortcutKeys = Keys.Control | Keys.Z;
         mEditRedoTSMI.ShortcutKeys = Keys.Control | Keys.Y;
         mEditSelectAllTSMI.ShortcutKeys = Keys.Control | Keys.A;
         mEditSelectNoneTSMI.ShortcutKeys = Keys.Control | Keys.Shift | Keys.A;
         mEditCutTSMI.ShortcutKeys = Keys.Control | Keys.X;
         mEditDeleteTSMI.ShortcutKeys = Keys.Delete;
         mEditPasteTSMI.ShortcutKeys = Keys.Control | Keys.V;
         mEditTrimToBeginningTSMI.ShortcutKeys = Keys.Control | Keys.Alt | Keys.X;
         mEditTrimToEndTSMI.ShortcutKeys = Keys.Control | Keys.Shift | Keys.X;
         mEditCopyTSMI.ShortcutKeys = Keys.Control | Keys.C;
         mEditCopyAllTSMI.ShortcutKeys = Keys.Control | Keys.Shift | Keys.C;
         mEditCopyToBeginningTSMI.ShortcutKeys = Keys.Control | Keys.Shift | Keys.Home;
         mEditCopyToEndTSMI.ShortcutKeys = Keys.Control | Keys.Shift | Keys.End;
         mEditFindTSMI.ShortcutKeys = Keys.Control | Keys.F;
         mEditFindNextTSMI.ShortcutKeys = Keys.Control | Keys.Alt | Keys.F;
         mEditFindPreviousTSMI.ShortcutKeys = Keys.Control | Keys.Shift | Keys.Alt | Keys.F;
         mEditReplaceTSMI.ShortcutKeys = Keys.Control | Keys.H;
         mEditGoToTSMI.ShortcutKeys = Keys.Control | Keys.G;
         mEditWordWrapTSMI.ShortcutKeys = Keys.Control | Keys.W;
         mTargetedTSMI.ShortcutKeys = Keys.Control | Keys.D;
         mRetargetTSMI.ShortcutKeys = Keys.Control | Keys.E;
         mFeaturesTSMI.ShortcutKeys = Keys.Control | Keys.J;
         mFiftyTSMI.ShortcutKeys = Keys.Control | Keys.Q;
         mMinimalTSMI.ShortcutKeys = Keys.Control | Keys.D0;
         mOpaqueTSMI.ShortcutKeys = Keys.Control | Keys.D1;
         mSeventyFiveTSMI.ShortcutKeys = Keys.Control | Keys.D2;
         mThemeEditTSMI.ShortcutKeys = Keys.Control | Keys.D3;
         mThirtyTSMI.ShortcutKeys = Keys.Control | Keys.D4;
         mTransparentTSMI.ShortcutKeys = Keys.Control | Keys.D5;
         mPlainTextTSMI.ShortcutKeys = Keys.Control | Keys.D6;
         mCSharpTSMI.ShortcutKeys = Keys.Control | Keys.D7;
         mCTSMI.ShortcutKeys = Keys.Control | Keys.D8;
         mCppTSMI.ShortcutKeys = Keys.Control | Keys.D9;
         mBasicTSMI.ShortcutKeys = Keys.Control | Keys.Oemtilde;
         mFSharpTSMI.ShortcutKeys = Keys.Control | Keys.OemMinus;
         mHtmlTSMI.ShortcutKeys = Keys.Control | Keys.Oemplus;
         mCssTSMI.ShortcutKeys = Keys.Control | Keys.OemOpenBrackets;
         mXmlTSMI.ShortcutKeys = Keys.Control | Keys.Oem6;
         mJsonTSMI.ShortcutKeys = Keys.Control | Keys.Oem1;
         mPowerShellTSMI.ShortcutKeys = Keys.Control | Keys.Oem7;
         mBatchTSMI.ShortcutKeys = Keys.Control | Keys.Oemcomma;
         mSqlTSMI.ShortcutKeys = Keys.Control | Keys.OemPeriod;
         mMarkdownTSMI.ShortcutKeys = Keys.Control | Keys.Down;
         mPythonTSMI.ShortcutKeys = Keys.Control | Keys.OemQuestion;
         mContextUndoTSMI.ShortcutKeys = Keys.Control | Keys.Z;
         mContextRedoTSMI.ShortcutKeys = Keys.Control | Keys.Y;
         mContextSelectAllTSMI.ShortcutKeys = Keys.Control | Keys.A;
         mContextSelectNoneTSMI.ShortcutKeys = Keys.Control | Keys.Shift | Keys.A;
         mContextCutTSMI.ShortcutKeys = Keys.Control | Keys.X;
         mContextDeleteTSMI.ShortcutKeys = Keys.Delete;
         mContextPasteTSMI.ShortcutKeys = Keys.Control | Keys.V;
         //DEBUG efm5 2026 05 14 these four don't currently exist
         //mContextTrimToBeginningTSMI.ShortcutKeys = Keys.Control | Keys.Alt | Keys.X;
         //mContextTrimToEndTSMI.ShortcutKeys = Keys.Control | Keys.Shift | Keys.X;
         mContextCopyTSMI.ShortcutKeys = Keys.Control | Keys.C;
         mContextCopyAllTSMI.ShortcutKeys = Keys.Control | Keys.Shift | Keys.C;
         //mContextCopyToBeginningTSMI.ShortcutKeys = Keys.Control | Keys.Shift | Keys.Home;
         //mContextCopyToEndTSMI.ShortcutKeys = Keys.Control | Keys.Shift | Keys.End;
         mContextFindTSMI.ShortcutKeys = Keys.Control | Keys.F;
         mContextFindNextTSMI.ShortcutKeys = Keys.Control | Keys.Alt | Keys.F;
         mContextFindPreviousTSMI.ShortcutKeys = Keys.Control | Keys.Shift | Keys.Alt | Keys.F;
         mContextReplaceTSMI.ShortcutKeys = Keys.Control | Keys.Shift | Keys.F;
         mContextGoToTSMI.ShortcutKeys = Keys.Control | Keys.G;
         //mContextWordWrapTSMI.ShortcutKeys = Keys.Control | Keys.W;
         // --- rich text box, buttons, and coding TSMIs ---
         mRichTextBox.Multiline = true;
         mRichTextBox.ScrollBars = RichTextBoxScrollBars.Both;
         mRichTextBox.AcceptsTab = true;
         mRichTextBox.WordWrap = false;
         mRichTextBox.Anchor = mAnchorTopLeftBottomRight;
         mRichTextBox.Name = "mainTextBox";
         mRichTextBox.TabIndex = mTabIndex++;
         mRichTextBox.ContextMenuStrip = mContextMenuStrip;
         mSendAllButton.Text = "&Send All";
         mSendAllButton.Name = "sendAllButton";
         mSendAllButton.TabIndex = mTabIndex++;
         mSendAllButton.AutoSize = true;
         mSendAllButton.AutoSizeMode = AutoSizeMode.GrowAndShrink;
         mSendAllButton.Tag = PasteMode.SendAll;
         mSendAllButton.Click += TransMove_Click;
         mPasteSelectedButton.Text = "&Paste Selected";
         mPasteSelectedButton.Name = "pasteSelectedButton";
         mPasteSelectedButton.TabIndex = mTabIndex++;
         mPasteSelectedButton.AutoSize = true;
         mPasteSelectedButton.AutoSizeMode = AutoSizeMode.GrowAndShrink;
         mPasteSelectedButton.Tag = PasteMode.PasteSelected;
         mPasteSelectedButton.Click += TransMove_Click;
         mGetAllButton.Text = "Get &All";
         mGetAllButton.Name = "getAllButton";
         mGetAllButton.TabIndex = mTabIndex++;
         mGetAllButton.AutoSize = true;
         mGetAllButton.AutoSizeMode = AutoSizeMode.GrowAndShrink;
         mGetAllButton.Tag = PasteMode.GetAll;
         mGetAllButton.Click += TransMove_Click;
         mGetSelectedButton.Text = "&Get Selected";
         mGetSelectedButton.Name = "getSelectedButton";
         mGetSelectedButton.TabIndex = mTabIndex++;
         mGetSelectedButton.AutoSize = true;
         mGetSelectedButton.AutoSizeMode = AutoSizeMode.GrowAndShrink;
         mGetSelectedButton.Tag = PasteMode.GetSelected;
         mGetSelectedButton.Click += TransMove_Click;
         mTargetingLabel.Name = "targetingLabel";
         mTargetingLabel.Text = string.Empty;
         mTargetingLabel.ImageAlign = ContentAlignment.MiddleLeft;
         mTargetingLabel.TextAlign = ContentAlignment.MiddleRight;
         mTargetingLabel.TabIndex = mTabIndex++;
         mVersionLabel.Name = "versionLabel";
         mVersionLabel.Text = "v: " + mVersionString;
         mVersionLabel.AutoSize = true;
         mVersionLabel.TextAlign = ContentAlignment.MiddleLeft;
         mVersionLabel.TabIndex = mTabIndex++;
         mRevertButton.Text = "&Revert";
         mRevertButton.Name = "revertButton";
         mRevertButton.TabIndex = mTabIndex++;
         mRevertButton.AutoSize = true;
         mRevertButton.AutoSizeMode = AutoSizeMode.GrowAndShrink;
         mRevertButton.Tag = PasteMode.SendAll;
         mRevertButton.Click += RevertButton_Click;
         // --- coding TSMI setup ---
         mCSharpCommentAddDoubleTSMI.Click += CFamilyAddDoubleTSMI_Click;
         mCSharpCommentAddDoubleTSMI.Name = "commentAddDoubleTSMI";
         mCSharpCommentAddDoubleTSMI.ShortcutKeys = Keys.Control | Keys.Alt | Keys.Shift | Keys.D;
         mCSharpCommentAddDoubleTSMI.Size = new Size(585, 36);
         mCSharpCommentAddDoubleTSMI.Text = "&Add Double";
         mCSharpAddNotImplementedTSMI.Click += CSharpAddNotImplementedTSMI_Click;
         mCSharpAddNotImplementedTSMI.Name = "addNotImplementedTSMI";
         mCSharpAddNotImplementedTSMI.ShortcutKeyDisplayString = "Ctrl+Alt+Shift+0 (zero)";
         mCSharpAddNotImplementedTSMI.ShortcutKeys = Keys.Control | Keys.Alt | Keys.Shift | Keys.D0;
         mCSharpAddNotImplementedTSMI.Size = new Size(585, 36);
         mCSharpAddNotImplementedTSMI.Text = "Add &Not Implemented";
         mCSharpCommentAddTripleTSMI.Click += CSharpAddTripleTSMI_Click;
         mCSharpCommentAddTripleTSMI.Name = "commentAddTripleTSMI";
         mCSharpCommentAddTripleTSMI.ShortcutKeys = Keys.Control | Keys.Alt | Keys.Shift | Keys.T;
         mCSharpCommentAddTripleTSMI.Size = new Size(585, 36);
         mCSharpCommentAddTripleTSMI.Text = "Add &Triple";
         mCPlusPlusCommentTSMI.Click += CFamilyBlockCommentTSMI_Click;
         mCPlusPlusCommentTSMI.Name = "cPlusPlusTSMI";
         mCPlusPlusCommentTSMI.ShortcutKeys = Keys.Control | Keys.Alt | Keys.Shift | Keys.C;
         mCPlusPlusCommentTSMI.Size = new Size(585, 36);
         mCPlusPlusCommentTSMI.Text = "&C++";
         mCSharpExpressionBodiedMethodTSMI.Click += CSharpExpressionBodiedMethodTSMI_Click;
         mCSharpExpressionBodiedMethodTSMI.Name = "expressionBodiedMethodTSMI";
         mCSharpExpressionBodiedMethodTSMI.ShortcutKeys = Keys.Control | Keys.Alt | Keys.Shift | Keys.D8;
         mCSharpExpressionBodiedMethodTSMI.Size = new Size(585, 36);
         mCSharpExpressionBodiedMethodTSMI.Text = "Expression-&Bodied Method";
         mCSharpCommentOutTSMI.Click += CFamilyCommentOutTSMI_Click;
         mCSharpCommentOutTSMI.Name = "commentOutTSMI";
         mCSharpCommentOutTSMI.ShortcutKeys = Keys.Control | Keys.Alt | Keys.Shift | Keys.D7;
         mCSharpCommentOutTSMI.Size = new Size(585, 36);
         mCSharpCommentOutTSMI.Text = "Comment &Out";
         mCSharpWrapTSMI.Click += CFamilyWrapCommentTSMI_Click;
         mCSharpWrapTSMI.Name = "commentWrapTSMI";
         mCSharpWrapTSMI.ShortcutKeys = Keys.Control | Keys.Alt | Keys.Shift | Keys.W;
         mCSharpWrapTSMI.Size = new Size(585, 36);
         mCSharpWrapTSMI.Text = "&Wrap";
         mCSharpCommentRemoveTSMI.Click += CFamilyCommentRemoveTSMI_Click;
         mCSharpCommentRemoveTSMI.Name = "commentRemoveTSMI";
         mCSharpCommentRemoveTSMI.ShortcutKeys = Keys.Control | Keys.Alt | Keys.Shift | Keys.R;
         mCSharpCommentRemoveTSMI.Size = new Size(585, 36);
         mCSharpCommentRemoveTSMI.Text = "&Remove";
         mCSharpReverseEqualityTSMI.Click += CSharpReverseEqualityTSMI_Click;
         mCSharpReverseEqualityTSMI.Name = "reverseEqualityTSMI";
         mCSharpReverseEqualityTSMI.ShortcutKeys = Keys.Control | Keys.Alt | Keys.Shift | Keys.D1;
         mCSharpReverseEqualityTSMI.Size = new Size(585, 36);
         mCSharpReverseEqualityTSMI.Text = "Reverse &Equality";
         mConvertVBToCSharpCommentTSMI.Click += ConvertVBToCSharpCommentTSMI_Click;
         mConvertVBToCSharpCommentTSMI.Name = "convertVBToCSharpCommentTSMI";
         mConvertVBToCSharpCommentTSMI.Size = new Size(585, 36);
         mConvertVBToCSharpCommentTSMI.Text = "&VB to C# Comment";
         mBasicAddSingleQuoteTSMI.Click += BasicAddSingleQuoteTSMI_Click;
         mBasicAddSingleQuoteTSMI.Name = "basicAddSingleQuoteTSMI";
         mBasicAddSingleQuoteTSMI.Size = new Size(585, 36);
         mBasicAddSingleQuoteTSMI.Text = "&Add Single Quote";
         mBasicConvertCSharpToVBCommentTSMI.Click += BasicConvertCSharpToVBCommentTSMI_Click;
         mBasicConvertCSharpToVBCommentTSMI.Name = "basicConvertCSharpToVBCommentTSMI";
         mBasicConvertCSharpToVBCommentTSMI.Size = new Size(585, 36);
         mBasicConvertCSharpToVBCommentTSMI.Text = "&C# to VB Comment";
         mBasicReverseEqualityTSMI.Click += BasicReverseEqualityTSMI_Click;
         mBasicReverseEqualityTSMI.Name = "basicReverseEqualityTSMI";
         mBasicReverseEqualityTSMI.Size = new Size(585, 36);
         mBasicReverseEqualityTSMI.Text = "&Reverse Equality";
         mBasicRemoveLineContinuationTSMI.Click += BasicRemoveLineContinuationTSMI_Click;
         mBasicRemoveLineContinuationTSMI.Name = "basicRemoveLineContinuationTSMI";
         mBasicRemoveLineContinuationTSMI.Size = new Size(585, 36);
         mBasicRemoveLineContinuationTSMI.Text = "Remove &Line Continuation";
         mBasicConvertBooleansTSMI.Click += BasicConvertBooleansTSMI_Click;
         mBasicConvertBooleansTSMI.Name = "basicConvertBooleansTSMI";
         mBasicConvertBooleansTSMI.Size = new Size(585, 36);
         mBasicConvertBooleansTSMI.Text = "Convert &Booleans";
         mBasicConvertNullNothingTSMI.Click += BasicConvertNullNothingTSMI_Click;
         mBasicConvertNullNothingTSMI.Name = "basicConvertNullNothingTSMI";
         mBasicConvertNullNothingTSMI.Size = new Size(585, 36);
         mBasicConvertNullNothingTSMI.Text = "Convert &Null/Nothing";
         mBasicConvertLogicalOperatorsTSMI.Click += BasicConvertLogicalOperatorsTSMI_Click;
         mBasicConvertLogicalOperatorsTSMI.Name = "basicConvertLogicalOperatorsTSMI";
         mBasicConvertLogicalOperatorsTSMI.Size = new Size(585, 36);
         mBasicConvertLogicalOperatorsTSMI.Text = "Convert Logical &Operators";
         mFSharpBlockCommentTSMI.Click += FSharpBlockCommentTSMI_Click;
         mFSharpBlockCommentTSMI.Name = "fSharpBlockCommentTSMI";
         mFSharpBlockCommentTSMI.Size = new Size(585, 36);
         mFSharpBlockCommentTSMI.Text = "&Block Comment (* *)";
         mFSharpAddCommentTSMI.Click += FSharpAddCommentTSMI_Click;
         mFSharpAddCommentTSMI.Name = "fSharpAddCommentTSMI";
         mFSharpAddCommentTSMI.Size = new Size(585, 36);
         mFSharpAddCommentTSMI.Text = "&Add Comment (//)";
         mFSharpAddMutableTSMI.Click += FSharpAddMutableTSMI_Click;
         mFSharpAddMutableTSMI.Name = "fSharpAddMutableTSMI";
         mFSharpAddMutableTSMI.Size = new Size(585, 36);
         mFSharpAddMutableTSMI.Text = "Add &Mutable";
         mFSharpAddIgnoreTSMI.Click += FSharpAddIgnoreTSMI_Click;
         mFSharpAddIgnoreTSMI.Name = "fSharpAddIgnoreTSMI";
         mFSharpAddIgnoreTSMI.Size = new Size(585, 36);
         mFSharpAddIgnoreTSMI.Text = "Add |> &ignore";
         mFSharpConvertNullNoneTSMI.Click += FSharpConvertNullNoneTSMI_Click;
         mFSharpConvertNullNoneTSMI.Name = "fSharpConvertNullNoneTSMI";
         mFSharpConvertNullNoneTSMI.Size = new Size(585, 36);
         mFSharpConvertNullNoneTSMI.Text = "&Convert null/None";
         mHTMLCommentTSMI.Click += HTMLCommentTSMI_Click;
         mHTMLCommentTSMI.Name = "htmlCommentTSMI";
         mHTMLCommentTSMI.Size = new Size(585, 36);
         mHTMLCommentTSMI.Text = "&Comment";
         mHTMLBoldTSMI.Click += HTMLBoldTSMI_Click;
         mHTMLBoldTSMI.Name = "htmlBoldTSMI";
         mHTMLBoldTSMI.Size = new Size(585, 36);
         mHTMLBoldTSMI.Text = "&Bold";
         mHTMLItalicTSMI.Click += HTMLItalicTSMI_Click;
         mHTMLItalicTSMI.Name = "htmlItalicTSMI";
         mHTMLItalicTSMI.Size = new Size(585, 36);
         mHTMLItalicTSMI.Text = "&Italic";
         mHTMLUnderlineTSMI.Click += HTMLUnderlineTSMI_Click;
         mHTMLUnderlineTSMI.Name = "htmlUnderlineTSMI";
         mHTMLUnderlineTSMI.Size = new Size(585, 36);
         mHTMLUnderlineTSMI.Text = "&Underline";
         mHTMLStrikethroughTSMI.Click += HTMLStrikethroughTSMI_Click;
         mHTMLStrikethroughTSMI.Name = "htmlStrikethroughTSMI";
         mHTMLStrikethroughTSMI.Size = new Size(585, 36);
         mHTMLStrikethroughTSMI.Text = "&Strikethrough";
         mHTMLBigTSMI.Click += HTMLBigTSMI_Click;
         mHTMLBigTSMI.Name = "htmlBigTSMI";
         mHTMLBigTSMI.Size = new Size(585, 36);
         mHTMLBigTSMI.Text = "Bi&g";
         mHTMLBigBigTSMI.Click += HTMLBigBigTSMI_Click;
         mHTMLBigBigTSMI.Name = "htmlBigBigTSMI";
         mHTMLBigBigTSMI.Size = new Size(585, 36);
         mHTMLBigBigTSMI.Text = "Big Big";
         mHTMLSmallTSMI.Click += HTMLSmallTSMI_Click;
         mHTMLSmallTSMI.Name = "htmlSmallTSMI";
         mHTMLSmallTSMI.Size = new Size(585, 36);
         mHTMLSmallTSMI.Text = "S&mall";
         mHTMLSmallSmallTSMI.Click += HTMLSmallSmallTSMI_Click;
         mHTMLSmallSmallTSMI.Name = "htmlSmallSmallTSMI";
         mHTMLSmallSmallTSMI.Size = new Size(585, 36);
         mHTMLSmallSmallTSMI.Text = "Sm&all";
         mHTMLMarkTSMI.Click += HTMLMarkTSMI_Click;
         mHTMLMarkTSMI.Name = "htmlMarkTSMI";
         mHTMLMarkTSMI.Size = new Size(585, 36);
         mHTMLMarkTSMI.Text = "Ma&rk";
         mHTMLSuperscriptTSMI.Click += HTMLSuperscriptTSMI_Click;
         mHTMLSuperscriptTSMI.Name = "htmlSuperscriptTSMI";
         mHTMLSuperscriptTSMI.Size = new Size(585, 36);
         mHTMLSuperscriptTSMI.Text = "Su&perscript";
         mHTMLSubscriptTSMI.Click += HTMLSubscriptTSMI_Click;
         mHTMLSubscriptTSMI.Name = "htmlSubscriptTSMI";
         mHTMLSubscriptTSMI.Size = new Size(585, 36);
         mHTMLSubscriptTSMI.Text = "Subscrip&t";
         mHTMLCodeTSMI.Click += HTMLCodeTSMI_Click;
         mHTMLCodeTSMI.Name = "htmlCodeTSMI";
         mHTMLCodeTSMI.Size = new Size(585, 36);
         mHTMLCodeTSMI.Text = "C&ode";
         mHTMLPreformattedTSMI.Click += HTMLPreformattedTSMI_Click;
         mHTMLPreformattedTSMI.Name = "htmlPreformattedTSMI";
         mHTMLPreformattedTSMI.Size = new Size(585, 36);
         mHTMLPreformattedTSMI.Text = "Pr&eformatted";
         mHTMLColorizeTSMI.Click += HTMLColorizeTSMI_Click;
         mHTMLColorizeTSMI.Name = "htmlColorizeTSMI";
         mHTMLColorizeTSMI.Size = new Size(585, 36);
         mHTMLColorizeTSMI.Text = "Co&lorize...";
         mCodingTSMI.Name = "codingTSMI";
         mCodingTSMI.Text = "&Coding";
         mCodingCFamilyTSMI.Name = "codingCFamilyTSMI";
         mCodingCFamilyTSMI.Text = "&C Family";
         mCodingBasicTSMI.Name = "codingBasicTSMI";
         mCodingBasicTSMI.Text = "&Basic";
         mCodingFSharpTSMI.Name = "codingFSharpTSMI";
         mCodingFSharpTSMI.Text = "&F#";
         mCodingHTMLTSMI.Name = "codingHTMLTSMI";
         mCodingHTMLTSMI.Text = "&HTML";
         mCSSBlockCommentTSMI.Click += CSSBlockCommentTSMI_Click;
         mCSSBlockCommentTSMI.Name = "cssBlockCommentTSMI";
         mCSSBlockCommentTSMI.Size = new Size(585, 36);
         mCSSBlockCommentTSMI.Text = "&Block Comment";
         mCSSCommentRemoveTSMI.Click += CSSCommentRemoveTSMI_Click;
         mCSSCommentRemoveTSMI.Name = "cssCommentRemoveTSMI";
         mCSSCommentRemoveTSMI.Size = new Size(585, 36);
         mCSSCommentRemoveTSMI.Text = "&Remove Comment";
         mCSSToggleImportantTSMI.Click += CSSToggleImportantTSMI_Click;
         mCSSToggleImportantTSMI.Name = "cssToggleImportantTSMI";
         mCSSToggleImportantTSMI.Size = new Size(585, 36);
         mCSSToggleImportantTSMI.Text = "&Toggle !important";
         mCSSConvertColorFormatTSMI.Click += CSSConvertColorFormatTSMI_Click;
         mCSSConvertColorFormatTSMI.Name = "cssConvertColorFormatTSMI";
         mCSSConvertColorFormatTSMI.Size = new Size(585, 36);
         mCSSConvertColorFormatTSMI.Text = "&Convert Color Format";
         mCodingCSSTSMI.Name = "codingCSSTSMI";
         mCodingCSSTSMI.Text = "C&SS";
         mCodingXMLTSMI.Name = "codingXMLTSMI";
         mCodingXMLTSMI.Text = "&XML";
         mXMLCommentTSMI.Click += XMLCommentTSMI_Click;
         mXMLCommentTSMI.Name = "xmlCommentTSMI";
         mXMLCommentTSMI.Size = new Size(585, 36);
         mXMLCommentTSMI.Text = "&Comment";
         mXMLRemoveCommentTSMI.Click += XMLRemoveCommentTSMI_Click;
         mXMLRemoveCommentTSMI.Name = "xmlRemoveCommentTSMI";
         mXMLRemoveCommentTSMI.Size = new Size(585, 36);
         mXMLRemoveCommentTSMI.Text = "&Remove Comment";
         mXMLEscapeEntitiesTSMI.Click += XMLEscapeEntitiesTSMI_Click;
         mXMLEscapeEntitiesTSMI.Name = "xmlEscapeEntitiesTSMI";
         mXMLEscapeEntitiesTSMI.Size = new Size(585, 36);
         mXMLEscapeEntitiesTSMI.Text = "&Escape Entities";
         mXMLWrapCDataTSMI.Click += XMLWrapCDataTSMI_Click;
         mXMLWrapCDataTSMI.Name = "xmlWrapCDataTSMI";
         mXMLWrapCDataTSMI.Size = new Size(585, 36);
         mXMLWrapCDataTSMI.Text = "&Wrap CDATA";
         mXMLToggleSelfCloseTSMI.Click += XMLToggleSelfCloseTSMI_Click;
         mXMLToggleSelfCloseTSMI.Name = "xmlToggleSelfCloseTSMI";
         mXMLToggleSelfCloseTSMI.Size = new Size(585, 36);
         mXMLToggleSelfCloseTSMI.Text = "&Toggle Self-Close";
         mCodingJSONTSMI.Name = "codingJSONTSMI";
         mCodingJSONTSMI.Text = "&JSON";
         mJSONAddCommentTSMI.Click += JSONAddCommentTSMI_Click;
         mJSONAddCommentTSMI.Name = "jsonAddCommentTSMI";
         mJSONAddCommentTSMI.Size = new Size(585, 36);
         mJSONAddCommentTSMI.Text = "&Add Comment";
         mJSONBlockCommentTSMI.Click += JSONBlockCommentTSMI_Click;
         mJSONBlockCommentTSMI.Name = "jsonBlockCommentTSMI";
         mJSONBlockCommentTSMI.Size = new Size(585, 36);
         mJSONBlockCommentTSMI.Text = "&Block Comment";
         mJSONRemoveCommentTSMI.Click += JSONRemoveCommentTSMI_Click;
         mJSONRemoveCommentTSMI.Name = "jsonRemoveCommentTSMI";
         mJSONRemoveCommentTSMI.Size = new Size(585, 36);
         mJSONRemoveCommentTSMI.Text = "&Remove Comment";
         mJSONToggleQuotesTSMI.Click += JSONToggleQuotesTSMI_Click;
         mJSONToggleQuotesTSMI.Name = "jsonToggleQuotesTSMI";
         mJSONToggleQuotesTSMI.Size = new Size(585, 36);
         mJSONToggleQuotesTSMI.Text = "&Toggle Quotes";
         mJSONEscapeStringTSMI.Click += JSONEscapeStringTSMI_Click;
         mJSONEscapeStringTSMI.Name = "jsonEscapeStringTSMI";
         mJSONEscapeStringTSMI.Size = new Size(585, 36);
         mJSONEscapeStringTSMI.Text = "&Escape String";
         mJSONRemoveTrailingCommasTSMI.Click += JSONRemoveTrailingCommasTSMI_Click;
         mJSONRemoveTrailingCommasTSMI.Name = "jsonRemoveTrailingCommasTSMI";
         mJSONRemoveTrailingCommasTSMI.Size = new Size(585, 36);
         mJSONRemoveTrailingCommasTSMI.Text = "Remove Trailing &Commas";
         mCodingPowerShellTSMI.Name = "codingPowerShellTSMI";
         mCodingPowerShellTSMI.Text = "&PowerShell";
         mPowerShellAddCommentTSMI.Click += PowerShellAddCommentTSMI_Click;
         mPowerShellAddCommentTSMI.Name = "powerShellAddCommentTSMI";
         mPowerShellAddCommentTSMI.Size = new Size(585, 36);
         mPowerShellAddCommentTSMI.Text = "&Add Comment";
         mPowerShellBlockCommentTSMI.Click += PowerShellBlockCommentTSMI_Click;
         mPowerShellBlockCommentTSMI.Name = "powerShellBlockCommentTSMI";
         mPowerShellBlockCommentTSMI.Size = new Size(585, 36);
         mPowerShellBlockCommentTSMI.Text = "&Block Comment";
         mPowerShellRemoveCommentTSMI.Click += PowerShellRemoveCommentTSMI_Click;
         mPowerShellRemoveCommentTSMI.Name = "powerShellRemoveCommentTSMI";
         mPowerShellRemoveCommentTSMI.Size = new Size(585, 36);
         mPowerShellRemoveCommentTSMI.Text = "&Remove Comment";
         mPowerShellToggleBooleanTSMI.Click += PowerShellToggleBooleanTSMI_Click;
         mPowerShellToggleBooleanTSMI.Name = "powerShellToggleBooleanTSMI";
         mPowerShellToggleBooleanTSMI.Size = new Size(585, 36);
         mPowerShellToggleBooleanTSMI.Text = "&Toggle Boolean";
         mPowerShellToggleQuotesTSMI.Click += PowerShellToggleQuotesTSMI_Click;
         mPowerShellToggleQuotesTSMI.Name = "powerShellToggleQuotesTSMI";
         mPowerShellToggleQuotesTSMI.Size = new Size(585, 36);
         mPowerShellToggleQuotesTSMI.Text = "Toggle &Quotes";
         mCodingBatchTSMI.Name = "codingBatchTSMI";
         mCodingBatchTSMI.Text = "&Batch";
         mBatchAddCommentTSMI.Click += BatchAddCommentTSMI_Click;
         mBatchAddCommentTSMI.Name = "batchAddCommentTSMI";
         mBatchAddCommentTSMI.Size = new Size(585, 36);
         mBatchAddCommentTSMI.Text = "&Add Comment (REM)";
         mBatchAddColonCommentTSMI.Click += BatchAddColonCommentTSMI_Click;
         mBatchAddColonCommentTSMI.Name = "batchAddColonCommentTSMI";
         mBatchAddColonCommentTSMI.Size = new Size(585, 36);
         mBatchAddColonCommentTSMI.Text = "Add &Comment (::)";
         mBatchRemoveCommentTSMI.Click += BatchRemoveCommentTSMI_Click;
         mBatchRemoveCommentTSMI.Name = "batchRemoveCommentTSMI";
         mBatchRemoveCommentTSMI.Size = new Size(585, 36);
         mBatchRemoveCommentTSMI.Text = "&Remove Comment";
         mBatchToggleCommentStyleTSMI.Click += BatchToggleCommentStyleTSMI_Click;
         mBatchToggleCommentStyleTSMI.Name = "batchToggleCommentStyleTSMI";
         mBatchToggleCommentStyleTSMI.Size = new Size(585, 36);
         mBatchToggleCommentStyleTSMI.Text = "&Toggle Comment Style";
         mCodingSQLTSMI.Name = "codingSQLTSMI";
         mCodingSQLTSMI.Text = "S&QL";
         mSQLAddCommentTSMI.Click += SQLAddCommentTSMI_Click;
         mSQLAddCommentTSMI.Name = "sqlAddCommentTSMI";
         mSQLAddCommentTSMI.Size = new Size(585, 36);
         mSQLAddCommentTSMI.Text = "&Add Comment";
         mSQLBlockCommentTSMI.Click += SQLBlockCommentTSMI_Click;
         mSQLBlockCommentTSMI.Name = "sqlBlockCommentTSMI";
         mSQLBlockCommentTSMI.Size = new Size(585, 36);
         mSQLBlockCommentTSMI.Text = "&Block Comment";
         mSQLRemoveCommentTSMI.Click += SQLRemoveCommentTSMI_Click;
         mSQLRemoveCommentTSMI.Name = "sqlRemoveCommentTSMI";
         mSQLRemoveCommentTSMI.Size = new Size(585, 36);
         mSQLRemoveCommentTSMI.Text = "&Remove Comment";
         mSQLToggleNullCheckTSMI.Click += SQLToggleNullCheckTSMI_Click;
         mSQLToggleNullCheckTSMI.Name = "sqlToggleNullCheckTSMI";
         mSQLToggleNullCheckTSMI.Size = new Size(585, 36);
         mSQLToggleNullCheckTSMI.Text = "Toggle &NULL Check";
         mSQLToggleBooleanTSMI.Click += SQLToggleBooleanTSMI_Click;
         mSQLToggleBooleanTSMI.Name = "sqlToggleBooleanTSMI";
         mSQLToggleBooleanTSMI.Size = new Size(585, 36);
         mSQLToggleBooleanTSMI.Text = "&Toggle Boolean";
         mCodingMarkdownTSMI.Name = "codingMarkdownTSMI";
         mCodingMarkdownTSMI.Text = "&Markdown";
         mMarkdownCommentTSMI.Click += MarkdownCommentTSMI_Click;
         mMarkdownCommentTSMI.Name = "markdownCommentTSMI";
         mMarkdownCommentTSMI.Size = new Size(585, 36);
         mMarkdownCommentTSMI.Text = "&Comment";
         mMarkdownBoldTSMI.Click += MarkdownBoldTSMI_Click;
         mMarkdownBoldTSMI.Name = "markdownBoldTSMI";
         mMarkdownBoldTSMI.Size = new Size(585, 36);
         mMarkdownBoldTSMI.Text = "&Bold";
         mMarkdownItalicTSMI.Click += MarkdownItalicTSMI_Click;
         mMarkdownItalicTSMI.Name = "markdownItalicTSMI";
         mMarkdownItalicTSMI.Size = new Size(585, 36);
         mMarkdownItalicTSMI.Text = "&Italic";
         mMarkdownBoldItalicTSMI.Click += MarkdownBoldItalicTSMI_Click;
         mMarkdownBoldItalicTSMI.Name = "markdownBoldItalicTSMI";
         mMarkdownBoldItalicTSMI.Size = new Size(585, 36);
         mMarkdownBoldItalicTSMI.Text = "B&old Italic";
         mMarkdownStrikethroughTSMI.Click += MarkdownStrikethroughTSMI_Click;
         mMarkdownStrikethroughTSMI.Name = "markdownStrikethroughTSMI";
         mMarkdownStrikethroughTSMI.Size = new Size(585, 36);
         mMarkdownStrikethroughTSMI.Text = "&Strikethrough";
         mMarkdownCodeTSMI.Click += MarkdownCodeTSMI_Click;
         mMarkdownCodeTSMI.Name = "markdownCodeTSMI";
         mMarkdownCodeTSMI.Size = new Size(585, 36);
         mMarkdownCodeTSMI.Text = "Co&de";
         mMarkdownCodeBlockTSMI.Click += MarkdownCodeBlockTSMI_Click;
         mMarkdownCodeBlockTSMI.Name = "markdownCodeBlockTSMI";
         mMarkdownCodeBlockTSMI.Size = new Size(585, 36);
         mMarkdownCodeBlockTSMI.Text = "Code B&lock";
         mCodingPythonTSMI.Name = "codingPythonTSMI";
         mCodingPythonTSMI.Text = "&Python";
         mPythonAddCommentTSMI.Click += PythonAddCommentTSMI_Click;
         mPythonAddCommentTSMI.Name = "pythonAddCommentTSMI";
         mPythonAddCommentTSMI.Size = new Size(585, 36);
         mPythonAddCommentTSMI.Text = "&Add Comment";
         mPythonBlockCommentTSMI.Click += PythonBlockCommentTSMI_Click;
         mPythonBlockCommentTSMI.Name = "pythonBlockCommentTSMI";
         mPythonBlockCommentTSMI.Size = new Size(585, 36);
         mPythonBlockCommentTSMI.Text = "&Block Comment";
         mPythonRemoveCommentTSMI.Click += PythonRemoveCommentTSMI_Click;
         mPythonRemoveCommentTSMI.Name = "pythonRemoveCommentTSMI";
         mPythonRemoveCommentTSMI.Size = new Size(585, 36);
         mPythonRemoveCommentTSMI.Text = "&Remove Comment";
         mPythonToggleBooleanTSMI.Click += PythonToggleBooleanTSMI_Click;
         mPythonToggleBooleanTSMI.Name = "pythonToggleBooleanTSMI";
         mPythonToggleBooleanTSMI.Size = new Size(585, 36);
         mPythonToggleBooleanTSMI.Text = "&Toggle Boolean";
         mPythonConvertNullNoneTSMI.Click += PythonConvertNullNoneTSMI_Click;
         mPythonConvertNullNoneTSMI.Name = "pythonConvertNullNoneTSMI";
         mPythonConvertNullNoneTSMI.Size = new Size(585, 36);
         mPythonConvertNullNoneTSMI.Text = "&Convert null/None";
         // --- bottom panel wiring ---
         mMainBottomPanel.AddLeftControl(mSendAllButton);
         mMainBottomPanel.AddLeftControl(mPasteSelectedButton);
         mMainBottomPanel.AddLeftControl(mGetAllButton);
         mMainBottomPanel.AddLeftControl(mGetSelectedButton);
         mMainBottomPanel.AddLeftControl(mTargetingLabel); // must be last — stretches to fill
         mMainBottomPanel.AddRightControl(mVersionLabel);  // added first = leftmost of right group
         mMainBottomPanel.AddRightControl(mRevertButton);
         ThrowIfNull(mMainBottomPanel.mCancelButton, nameof(mMainBottomPanel.mCancelButton));
         ThrowIfNull(mMainBottomPanel.mHelpButton, nameof(mMainBottomPanel.mHelpButton));
         mMainBottomPanel.mHelpButton.Tag = new HelpTag(HelpContext.Main);
         mMainBottomPanel.mCancelButton.Click += ExitButton_Click;
         mScrollableMainPanel.Controls.AddRange([mRichTextBox, mMainBottomPanel, mMenuStrip!]);
         mActiveLayoutable = mMainBottomPanel;
         SuspendLayout();
         Controls.Add(mScrollableMainPanel);
         StartPosition = FormStartPosition.Manual;
         ClientSize = new Size(800, 800);
         MinimumSize = new Size(400, 300);
         Text = "DB Code";
         mMenuStrip.Dock = DockStyle.Top;
         mMenuStrip.Name = "menuStrip";
         mMenuStrip.TabIndex = mTabIndex++;
         mMenuStrip.ShowItemToolTips = true;
         mTargetingMenuItem.Name = "targetingMenuItem";
         mTargetingMenuItem.Text = "&Targeting";
         mVisibilityMenuItem.Name = "visibilityMenuItem";
         mVisibilityMenuItem.Text = "&Visibility";
         mModeMenuItem.Name = "modeMenuItem";
         mModeMenuItem.Text = "Mo&de";
         mLanguageMenuItem.Name = "languageMenuItem";
         mLanguageMenuItem.Text = "&Language";
         mOptionsMenuItem.Name = "optionsMenuItem";
         mOptionsMenuItem.Text = "&Options";
         mOptionsMenuItem.Click += Options_Click;
         mThemeMenuItem.Name = "themeMenuItem";
         mThemeMenuItem.Text = "The&me";
         mThemeEditPickTSMI.Name = "themeEditPickTSMI";
         mThemeEditPickTSMI.Text = "P&ick To Edit";
         mThemeEditPickTSMI.Click += ThemeEditPick_Click;
         mThemeEditCurrentTSMI.Name = "themeEditCurrentTSMI";
         mThemeEditCurrentTSMI.Text = "&Edit Current";
         mThemeEditCurrentTSMI.Click += ThemeEditCurrent_Click;
         mThemeDesignTSMI.Name = "themeDesignTSMI";
         mThemeDesignTSMI.Text = "&Design";
         mThemeDesignTSMI.Click += ThemeDesign_Click;
         mThemeEditTSMI.Name = "themeEditTSMI";
         mThemeEditTSMI.Text = "&Edit";
         mThemePickTSMI.Name = "themePickTSMI";
         mThemePickTSMI.Text = "&Pick";
         mHelpMenuItem.Name = "helpMenuItem";
         mHelpMenuItem.Text = "&Help";
         mHelpMenuItem.Tag = new HelpTag(HelpContext.Main);
         mHelpMenuItem.Click += Help_Click;
         mTargetedTSMI.Name = "targetedTSMI";
         mTargetedTSMI.Text = "&Targeted";
         mTargetedTSMI.CheckOnClick = true;
         mTargetedTSMI.Click += TargetedTSMI_Click;
         mRetargetTSMI.Name = "retargetTSMI";
         mRetargetTSMI.Text = "&Retarget";
         mRetargetTSMI.Click += RetargetTSMI_Click;
         mTransparentTSMI.Name = "transparentTSMI";
         mTransparentTSMI.Text = "&Transparent";
         mTransparentTSMI.Tag = 0.0;
         mTransparentTSMI.Click += VisibilityTSMI_Click;
         mThirtyTSMI.Name = "thirtyTSMI";
         mThirtyTSMI.Text = "&30%";
         mThirtyTSMI.Tag = 0.3;
         mThirtyTSMI.Click += VisibilityTSMI_Click;
         mFiftyTSMI.Name = "fiftyTSMI";
         mFiftyTSMI.Text = "&50%";
         mFiftyTSMI.Tag = 0.5;
         mFiftyTSMI.Click += VisibilityTSMI_Click;
         mSeventyFiveTSMI.Name = "seventyFiveTSMI";
         mSeventyFiveTSMI.Text = "&75%";
         mSeventyFiveTSMI.Tag = 0.75;
         mSeventyFiveTSMI.Click += VisibilityTSMI_Click;
         mOpaqueTSMI.Name = "opaqueTSMI";
         mOpaqueTSMI.Text = "&Opaque";
         mOpaqueTSMI.Tag = 1.0;
         mOpaqueTSMI.Click += VisibilityTSMI_Click;
         mMinimalTSMI.Name = "minimalTSMI";
         mMinimalTSMI.Text = "&Minimal";
         mMinimalTSMI.Click += MinimalTSMI_Click;
         mFeaturesTSMI.Name = "featuresTSMI";
         mFeaturesTSMI.Text = "&Features";
         mFeaturesTSMI.Checked = true;
         mFeaturesTSMI.Click += FeaturesTSMI_Click;
         mPlainTextTSMI.Name = "plaintextTSMI";
         mPlainTextTSMI.Text = "Plain&text";
         mPlainTextTSMI.Tag = LanguageKind.PlainText;
         mPlainTextTSMI.Click += LanguageTSMI_Click;
         mCSharpTSMI.Name = "cSharpTSMI";
         mCSharpTSMI.Text = "CSha&rp";
         mCSharpTSMI.Tag = LanguageKind.CSharp;
         mCSharpTSMI.Click += LanguageTSMI_Click;
         mCTSMI.Name = "cTSMI";
         mCTSMI.Text = "&C";
         mCTSMI.Tag = LanguageKind.C;
         mCTSMI.Click += LanguageTSMI_Click;
         mCppTSMI.Name = "cppTSMI";
         mCppTSMI.Text = "C&pp";
         mCppTSMI.Tag = LanguageKind.Cpp;
         mCppTSMI.Click += LanguageTSMI_Click;
         mBasicTSMI.Name = "basicTSMI";
         mBasicTSMI.Text = "&Basic";
         mBasicTSMI.Tag = LanguageKind.Basic;
         mBasicTSMI.Click += LanguageTSMI_Click;
         mFSharpTSMI.Name = "fSharpTSMI";
         mFSharpTSMI.Text = "&FSharp";
         mFSharpTSMI.Tag = LanguageKind.FSharp;
         mFSharpTSMI.Click += LanguageTSMI_Click;
         mHtmlTSMI.Name = "hTMLTSMI";
         mHtmlTSMI.Text = "&HTML";
         mHtmlTSMI.Tag = LanguageKind.Html;
         mHtmlTSMI.Click += LanguageTSMI_Click;
         mCssTSMI.Name = "cSSTSMI";
         mCssTSMI.Text = "C&SS";
         mCssTSMI.Tag = LanguageKind.Css;
         mCssTSMI.Click += LanguageTSMI_Click;
         mXmlTSMI.Name = "xMLTSMI";
         mXmlTSMI.Text = "&XML";
         mXmlTSMI.Tag = LanguageKind.Xml;
         mXmlTSMI.Click += LanguageTSMI_Click;
         mJsonTSMI.Name = "jSONTSMI";
         mJsonTSMI.Text = "&JSON";
         mJsonTSMI.Tag = LanguageKind.Json;
         mJsonTSMI.Click += LanguageTSMI_Click;
         mPowerShellTSMI.Name = "powerShellTSMI";
         mPowerShellTSMI.Text = "Po&werShell";
         mPowerShellTSMI.Tag = LanguageKind.PowerShell;
         mPowerShellTSMI.Click += LanguageTSMI_Click;
         mBatchTSMI.Name = "batchTSMI";
         mBatchTSMI.Text = "B&atch";
         mBatchTSMI.Tag = LanguageKind.Batch;
         mBatchTSMI.Click += LanguageTSMI_Click;
         mSqlTSMI.Name = "sQLTSMI";
         mSqlTSMI.Text = "S&QL";
         mSqlTSMI.Tag = LanguageKind.Sql;
         mSqlTSMI.Click += LanguageTSMI_Click;
         mMarkdownTSMI.Name = "markdownTSMI";
         mMarkdownTSMI.Text = "&Markdown";
         mMarkdownTSMI.Tag = LanguageKind.Markdown;
         mMarkdownTSMI.Click += LanguageTSMI_Click;
         mPythonTSMI.Name = "pythonTSMI";
         mPythonTSMI.Text = "P&ython";
         mPythonTSMI.Tag = LanguageKind.Python;
         mPythonTSMI.Click += LanguageTSMI_Click;
         mCurrentThemeIsTSMI.Name = "currentThemeIsTSMI";
         mCurrentThemeIsTSMI.Text = mCurrently + mCurrentTheme.mName;
         mContextUndoTSMI.Name = "contextUndoTSMI";
         mContextUndoTSMI.Text = "&Undo";
         mContextUndoTSMI.Click += Undo_Click;
         mContextRedoTSMI.Name = "contextRedoTSMI";
         mContextRedoTSMI.Text = "&Redo";
         mContextRedoTSMI.Click += Redo_Click;
         mContextCopyTSMI.Name = "contextCopyTSMI";
         mContextCopyTSMI.Text = "&Copy";
         mContextCopyTSMI.Click += Copy_Click;
         mContextCopyAllTSMI.Name = "contextCopyAllTSMI";
         mContextCopyAllTSMI.Text = "Copy &All";
         mContextCopyAllTSMI.Click += CopyAll_Click;
         mContextCutTSMI.Name = "contextCutTSMI";
         mContextCutTSMI.Text = "Cu&t";
         mContextCutTSMI.Click += Cut_Click;
         mContextDeleteTSMI.Name = "contextDeleteTSMI";
         mContextDeleteTSMI.Text = "&Delete";
         mContextDeleteTSMI.Click += Delete_Click;
         mContextPasteTSMI.Name = "contextPasteTSMI";
         mContextPasteTSMI.Text = "&Paste";
         mContextPasteTSMI.Click += Paste_Click;
         mContextSelectAllTSMI.Name = "contextSelectAllTSMI";
         mContextSelectAllTSMI.Text = "Select &All";
         mContextSelectAllTSMI.Click += SelectAll_Click;
         mContextSelectNoneTSMI.Name = "contextSelectNoneTSMI";
         mContextSelectNoneTSMI.Text = "Select &None";
         mContextSelectNoneTSMI.Click += SelectNone_Click;
         mContextFindTSMI.Name = "contextFindTSMI";
         mContextFindTSMI.Text = "&Find";
         mContextFindTSMI.Click += Find_Click;
         mContextFindNextTSMI.Name = "contextFindNextTSMI";
         mContextFindNextTSMI.Text = "Find Ne&xt";
         mContextFindNextTSMI.Click += FindNext_Click;
         mContextFindPreviousTSMI.Name = "contextFindPreviousTSMI";
         mContextFindPreviousTSMI.Text = "Find Pre&vious";
         mContextFindPreviousTSMI.Click += FindPrevious_Click;
         mContextReplaceTSMI.Name = "contextReplaceTSMI";
         mContextReplaceTSMI.Text = "Re&place";
         mContextReplaceTSMI.Click += Replace_Click;
         mContextGoToTSMI.Name = "contextGoToTSMI";
         mContextGoToTSMI.Text = "&GoTo";
         mContextGoToTSMI.Click += GoTo_Click;
         mEditMenuItem.Name = "editTSMI";
         mEditMenuItem.Text = "&Edit";
         mEditUndoTSMI.Name = "editUndoTSMI";
         mEditUndoTSMI.Text = "&Undo";
         mEditUndoTSMI.Click += Undo_Click;
         mEditRedoTSMI.Name = "editRedoTSMI";
         mEditRedoTSMI.Text = "&Redo";
         mEditRedoTSMI.Click += Redo_Click;
         mEditCutTSMI.Name = "editCutTSMI";
         mEditCutTSMI.Text = "Cu&t";
         mEditCutTSMI.Click += Cut_Click;
         mEditDeleteTSMI.Name = "editDeleteTSMI";
         mEditDeleteTSMI.Text = "&Delete";
         mEditDeleteTSMI.Click += Delete_Click;
         mEditPasteTSMI.Name = "editPasteTSMI";
         mEditPasteTSMI.Text = "&Paste";
         mEditPasteTSMI.Click += Paste_Click;
         mEditSelectAllTSMI.Name = "editSelectAllTSMI";
         mEditSelectAllTSMI.Text = "Select &All";
         mEditSelectAllTSMI.Click += SelectAll_Click;
         mEditSelectNoneTSMI.Name = "editSelectNoneTSMI";
         mEditSelectNoneTSMI.Text = "Select &None";
         mEditSelectNoneTSMI.Click += SelectNone_Click;
         mEditTrimToBeginningTSMI.Name = "editTrimToBeginningTSMI";
         mEditTrimToBeginningTSMI.Text = "Trim To &Beginning";
         mEditTrimToBeginningTSMI.Click += TrimToBeginning_Click;
         mEditTrimToEndTSMI.Name = "editTrimToEndTSMI";
         mEditTrimToEndTSMI.Text = "Tr&im To End";
         mEditTrimToEndTSMI.Click += TrimToEnd_Click;
         mEditCopyTSMI.Name = "editCopyTSMI";
         mEditCopyTSMI.Text = "&Copy";
         mEditCopyTSMI.Click += Copy_Click;
         mEditCopyAllTSMI.Name = "editCopyAllTSMI";
         mEditCopyAllTSMI.Text = "Cop&y All";
         mEditCopyAllTSMI.Click += CopyAll_Click;
         mEditCopyToBeginningTSMI.Name = "editCopyToBeginningTSMI";
         mEditCopyToBeginningTSMI.Text = "C&opy To Beginning";
         mEditCopyToBeginningTSMI.Click += CopyToBeginning_Click;
         mEditCopyToEndTSMI.Name = "editCopyToEndTSMI";
         mEditCopyToEndTSMI.Text = "Copy To &End";
         mEditCopyToEndTSMI.Click += CopyToEnd_Click;
         mEditFindTSMI.Name = "editFindTSMI";
         mEditFindTSMI.Text = "&Find";
         mEditFindTSMI.Click += Find_Click;
         mEditFindNextTSMI.Name = "editFindNextTSMI";
         mEditFindNextTSMI.Text = "Find Ne&xt";
         mEditFindNextTSMI.Click += FindNext_Click;
         mEditFindPreviousTSMI.Name = "editFindPreviousTSMI";
         mEditFindPreviousTSMI.Text = "Find Pre&vious";
         mEditFindPreviousTSMI.Click += FindPrevious_Click;
         mEditReplaceTSMI.Name = "editReplaceTSMI";
         mEditReplaceTSMI.Text = "Rep&lace";
         mEditReplaceTSMI.Click += Replace_Click;
         mEditGoToTSMI.Name = "editGoToTSMI";
         mEditGoToTSMI.Text = "&GoTo";
         mEditGoToTSMI.Click += GoTo_Click;
         mEditWordWrapTSMI.Name = "editWordWrapTSMI";
         mEditWordWrapTSMI.Text = "&Wordwrap";
         mEditWordWrapTSMI.Click += WordWrap_Click;
         mThemePickTSMI.DropDownItems.AddRange([mThemeEditPickTSMI, mThemeEditCurrentTSMI]);
         mVisibilityMenuItem.DropDownItems.AddRange([mTransparentTSMI, mThirtyTSMI, mFiftyTSMI,
            mSeventyFiveTSMI, mOpaqueTSMI]);
         mModeMenuItem.DropDownItems.AddRange([mMinimalTSMI, mFeaturesTSMI]);
         mLanguageMenuItem.DropDownItems.AddRange([mPlainTextTSMI, mCSharpTSMI, mCTSMI, mCppTSMI,
            mBasicTSMI, mFSharpTSMI, mHtmlTSMI, mCssTSMI, mXmlTSMI, mJsonTSMI, mPowerShellTSMI, mBatchTSMI,
            mSqlTSMI, mMarkdownTSMI, mPythonTSMI]);
         mEditMenuItem.DropDownItems.AddRange([mEditUndoTSMI, mEditRedoTSMI, toolStripSeparator2,
            mEditSelectAllTSMI, mEditSelectNoneTSMI, toolStripSeparator3, mEditCutTSMI, mEditDeleteTSMI,
            mEditTrimToBeginningTSMI, mEditTrimToEndTSMI, toolStripSeparator4, mEditCopyTSMI, mEditCopyAllTSMI,
            mEditCopyToBeginningTSMI, mEditCopyToEndTSMI, mEditPasteTSMI, toolStripSeparator5, mEditFindTSMI,
            mEditFindNextTSMI, mEditFindPreviousTSMI, mEditReplaceTSMI, toolStripSeparator6, mEditGoToTSMI,
            mEditWordWrapTSMI]);
         mCodingTSMI.DropDownItems.AddRange([mCodingCFamilyTSMI, mCodingBasicTSMI, mCodingFSharpTSMI,
            mCodingHTMLTSMI, mCodingCSSTSMI, mCodingXMLTSMI, mCodingJSONTSMI, mCodingPowerShellTSMI,
            mCodingBatchTSMI, mCodingSQLTSMI, mCodingMarkdownTSMI, mCodingPythonTSMI]);
         mCodingCFamilyTSMI.DropDownItems.AddRange([
            mCSharpCommentAddDoubleTSMI, mCSharpCommentAddTripleTSMI, mCPlusPlusCommentTSMI, mCSharpCommentOutTSMI,
            mCSharpCommentRemoveTSMI, mCSharpWrapTSMI, mConvertVBToCSharpCommentTSMI, toolStripSeparator10,
            mCSharpAddNotImplementedTSMI, mCSharpReverseEqualityTSMI, mCSharpExpressionBodiedMethodTSMI]);
         mCodingBasicTSMI.DropDownItems.AddRange([
            mBasicAddSingleQuoteTSMI, mBasicConvertCSharpToVBCommentTSMI, toolStripSeparator11,
            mBasicReverseEqualityTSMI, mBasicRemoveLineContinuationTSMI, toolStripSeparator12,
            mBasicConvertBooleansTSMI, mBasicConvertNullNothingTSMI, mBasicConvertLogicalOperatorsTSMI]);
         mCodingFSharpTSMI.DropDownItems.AddRange([
            mFSharpBlockCommentTSMI, mFSharpAddCommentTSMI, toolStripSeparator17,
            mFSharpAddMutableTSMI, mFSharpAddIgnoreTSMI, toolStripSeparator18,
            mFSharpConvertNullNoneTSMI]);
         mCodingHTMLTSMI.DropDownItems.AddRange([
            mHTMLCommentTSMI, toolStripSeparator13,
            mHTMLBoldTSMI, mHTMLItalicTSMI, mHTMLUnderlineTSMI, mHTMLStrikethroughTSMI, toolStripSeparator14,
            mHTMLBigTSMI, mHTMLBigBigTSMI, mHTMLSmallTSMI, mHTMLSmallSmallTSMI, toolStripSeparator15,
            mHTMLMarkTSMI, mHTMLSuperscriptTSMI, mHTMLSubscriptTSMI, mHTMLCodeTSMI, mHTMLPreformattedTSMI,
            toolStripSeparator16, mHTMLColorizeTSMI]);
         mCodingCSSTSMI.DropDownItems.AddRange([
            mCSSBlockCommentTSMI, mCSSCommentRemoveTSMI, toolStripSeparator19,
            mCSSToggleImportantTSMI, mCSSConvertColorFormatTSMI]);
         mCodingXMLTSMI.DropDownItems.AddRange([
            mXMLCommentTSMI, mXMLRemoveCommentTSMI, toolStripSeparator20,
            mXMLEscapeEntitiesTSMI, mXMLWrapCDataTSMI, toolStripSeparator21,
            mXMLToggleSelfCloseTSMI]);
         mCodingJSONTSMI.DropDownItems.AddRange([
            mJSONAddCommentTSMI, mJSONBlockCommentTSMI, mJSONRemoveCommentTSMI, toolStripSeparator22,
            mJSONToggleQuotesTSMI, mJSONEscapeStringTSMI, toolStripSeparator23,
            mJSONRemoveTrailingCommasTSMI]);
         mCodingPowerShellTSMI.DropDownItems.AddRange([
            mPowerShellAddCommentTSMI, mPowerShellBlockCommentTSMI, mPowerShellRemoveCommentTSMI,
            toolStripSeparator24, mPowerShellToggleBooleanTSMI, mPowerShellToggleQuotesTSMI]);
         mCodingBatchTSMI.DropDownItems.AddRange([
            mBatchAddCommentTSMI, mBatchAddColonCommentTSMI, mBatchRemoveCommentTSMI,
            toolStripSeparator25, mBatchToggleCommentStyleTSMI]);
         mCodingSQLTSMI.DropDownItems.AddRange([
            mSQLAddCommentTSMI, mSQLBlockCommentTSMI, mSQLRemoveCommentTSMI,
            toolStripSeparator26, mSQLToggleNullCheckTSMI, mSQLToggleBooleanTSMI]);
         mCodingMarkdownTSMI.DropDownItems.AddRange([
            mMarkdownCommentTSMI, toolStripSeparator27,
            mMarkdownBoldTSMI, mMarkdownItalicTSMI, mMarkdownBoldItalicTSMI, mMarkdownStrikethroughTSMI,
            toolStripSeparator28, mMarkdownCodeTSMI, mMarkdownCodeBlockTSMI]);
         mCodingPythonTSMI.DropDownItems.AddRange([
            mPythonAddCommentTSMI, mPythonBlockCommentTSMI, mPythonRemoveCommentTSMI,
            toolStripSeparator29, mPythonToggleBooleanTSMI, mPythonConvertNullNoneTSMI]);
         mMenuStrip.Items.AddRange([mEditMenuItem, mTargetingMenuItem, mVisibilityMenuItem, mModeMenuItem,
            mLanguageMenuItem, mCodingTSMI, mOptionsMenuItem, mThemeMenuItem, mHelpMenuItem]);
         mContextMenuStrip.Items.AddRange([mContextUndoTSMI, mContextRedoTSMI, mContextCopyAllTSMI,
            mContextCopyTSMI, mContextCutTSMI, mContextDeleteTSMI, mContextPasteTSMI, toolStripSeparator7,
            mContextSelectAllTSMI, mContextSelectNoneTSMI, toolStripSeparator8, mContextFindTSMI,
            mContextFindNextTSMI, mContextFindPreviousTSMI, mContextReplaceTSMI, toolStripSeparator9,
            mContextGoToTSMI]);
         mThemeMenuItem.DropDownItems.AddRange([mCurrentThemeIsTSMI, toolStripSeparator1, mThemePickTSMI,
            mThemeDesignTSMI, mThemeEditTSMI]);
         mTargetingMenuItem.DropDownItems.AddRange([mTargetedTSMI, mRetargetTSMI]);
         Load += MainForm_Load;
         FormClosing += MainForm_FormClosing;
         mHighlighterEngine = new HighlighterEngine(mRichTextBox, mCurrentLanguage);
         mMainBottomPanel.Dock = DockStyle.Bottom;
         mRichTextBox.Dock = DockStyle.Fill;
         mRichTextBox.TextChanged += OnEditorTextChanged;
         InitializeIcon();
         CheckLanguage();
         AdjustForThemeFont(mCurrentTheme.mFonts[(int)FontUsage.Interface]);
         ApplyTheme();
         UpdateTargetingStatusLabel();
         ResumeLayout(false);
         PerformLayout();
      }

      private static void ValidateAllFields() {
         // Core UI
         ThrowIfNull(mCurrentTheme, nameof(mCurrentTheme));
         ThrowIfNull(mScrollableMainPanel, nameof(mScrollableMainPanel));
         ThrowIfNull(mRichTextBox, nameof(mRichTextBox));
         ThrowIfNull(mMainBottomPanel, nameof(mMainBottomPanel));
         ThrowIfNull(mMenuStrip, nameof(mMenuStrip));
         ThrowIfNull(mContextMenuStrip, nameof(mContextMenuStrip));
         // Buttons and labels
         ThrowIfNull(mSendAllButton, nameof(mSendAllButton));
         ThrowIfNull(mPasteSelectedButton, nameof(mPasteSelectedButton));
         ThrowIfNull(mGetAllButton, nameof(mGetAllButton));
         ThrowIfNull(mGetSelectedButton, nameof(mGetSelectedButton));
         ThrowIfNull(mTargetingLabel, nameof(mTargetingLabel));
         ThrowIfNull(mVersionLabel, nameof(mVersionLabel));
         ThrowIfNull(mRevertButton, nameof(mRevertButton));
         // Top-level menu items
         ThrowIfNull(mTargetingMenuItem, nameof(mTargetingMenuItem));
         ThrowIfNull(mVisibilityMenuItem, nameof(mVisibilityMenuItem));
         ThrowIfNull(mModeMenuItem, nameof(mModeMenuItem));
         ThrowIfNull(mOptionsMenuItem, nameof(mOptionsMenuItem));
         ThrowIfNull(mLanguageMenuItem, nameof(mLanguageMenuItem));
         ThrowIfNull(mThemeMenuItem, nameof(mThemeMenuItem));
         ThrowIfNull(mHelpMenuItem, nameof(mHelpMenuItem));
         ThrowIfNull(mEditMenuItem, nameof(mEditMenuItem));
         // Theme menu
         ThrowIfNull(mThemeEditPickTSMI, nameof(mThemeEditPickTSMI));
         ThrowIfNull(mThemeEditCurrentTSMI, nameof(mThemeEditCurrentTSMI));
         ThrowIfNull(mThemeDesignTSMI, nameof(mThemeDesignTSMI));
         ThrowIfNull(mThemeEditTSMI, nameof(mThemeEditTSMI));
         ThrowIfNull(mThemePickTSMI, nameof(mThemePickTSMI));
         ThrowIfNull(mCurrentThemeIsTSMI, nameof(mCurrentThemeIsTSMI));
         // Targeting / visibility
         ThrowIfNull(mTargetedTSMI, nameof(mTargetedTSMI));
         ThrowIfNull(mRetargetTSMI, nameof(mRetargetTSMI));
         ThrowIfNull(mTransparentTSMI, nameof(mTransparentTSMI));
         ThrowIfNull(mThirtyTSMI, nameof(mThirtyTSMI));
         ThrowIfNull(mFiftyTSMI, nameof(mFiftyTSMI));
         ThrowIfNull(mSeventyFiveTSMI, nameof(mSeventyFiveTSMI));
         ThrowIfNull(mOpaqueTSMI, nameof(mOpaqueTSMI));
         // Mode
         ThrowIfNull(mMinimalTSMI, nameof(mMinimalTSMI));
         ThrowIfNull(mFeaturesTSMI, nameof(mFeaturesTSMI));
         // Language
         ThrowIfNull(mPlainTextTSMI, nameof(mPlainTextTSMI));
         ThrowIfNull(mCSharpTSMI, nameof(mCSharpTSMI));
         ThrowIfNull(mBasicTSMI, nameof(mBasicTSMI));
         ThrowIfNull(mFSharpTSMI, nameof(mFSharpTSMI));
         ThrowIfNull(mHtmlTSMI, nameof(mHtmlTSMI));
         ThrowIfNull(mCssTSMI, nameof(mCssTSMI));
         ThrowIfNull(mXmlTSMI, nameof(mXmlTSMI));
         ThrowIfNull(mJsonTSMI, nameof(mJsonTSMI));
         ThrowIfNull(mPowerShellTSMI, nameof(mPowerShellTSMI));
         ThrowIfNull(mBatchTSMI, nameof(mBatchTSMI));
         ThrowIfNull(mSqlTSMI, nameof(mSqlTSMI));
         ThrowIfNull(mMarkdownTSMI, nameof(mMarkdownTSMI));
         ThrowIfNull(mPythonTSMI, nameof(mPythonTSMI));
         ThrowIfNull(mCTSMI, nameof(mCTSMI));
         ThrowIfNull(mCppTSMI, nameof(mCppTSMI));
         // Context menu
         ThrowIfNull(mContextCopyTSMI, nameof(mContextCopyTSMI));
         ThrowIfNull(mContextCutTSMI, nameof(mContextCutTSMI));
         ThrowIfNull(mContextDeleteTSMI, nameof(mContextDeleteTSMI));
         ThrowIfNull(mContextPasteTSMI, nameof(mContextPasteTSMI));
         ThrowIfNull(mContextSelectAllTSMI, nameof(mContextSelectAllTSMI));
         ThrowIfNull(mContextSelectNoneTSMI, nameof(mContextSelectNoneTSMI));
         ThrowIfNull(mContextFindTSMI, nameof(mContextFindTSMI));
         ThrowIfNull(mContextFindNextTSMI, nameof(mContextFindNextTSMI));
         ThrowIfNull(mContextFindPreviousTSMI, nameof(mContextFindPreviousTSMI));
         ThrowIfNull(mContextReplaceTSMI, nameof(mContextReplaceTSMI));
         ThrowIfNull(mContextGoToTSMI, nameof(mContextGoToTSMI));
         ThrowIfNull(mContextUndoTSMI, nameof(mContextUndoTSMI));
         ThrowIfNull(mContextRedoTSMI, nameof(mContextRedoTSMI));
         ThrowIfNull(mContextCopyAllTSMI, nameof(mContextCopyAllTSMI));
         // Edit menu
         ThrowIfNull(mEditUndoTSMI, nameof(mEditUndoTSMI));
         ThrowIfNull(mEditRedoTSMI, nameof(mEditRedoTSMI));
         ThrowIfNull(mEditCutTSMI, nameof(mEditCutTSMI));
         ThrowIfNull(mEditDeleteTSMI, nameof(mEditDeleteTSMI));
         ThrowIfNull(mEditPasteTSMI, nameof(mEditPasteTSMI));
         ThrowIfNull(mEditCopyTSMI, nameof(mEditCopyTSMI));
         ThrowIfNull(mEditCopyAllTSMI, nameof(mEditCopyAllTSMI));
         ThrowIfNull(mEditCopyToBeginningTSMI, nameof(mEditCopyToBeginningTSMI));
         ThrowIfNull(mEditCopyToEndTSMI, nameof(mEditCopyToEndTSMI));
         ThrowIfNull(mEditSelectAllTSMI, nameof(mEditSelectAllTSMI));
         ThrowIfNull(mEditSelectNoneTSMI, nameof(mEditSelectNoneTSMI));
         ThrowIfNull(mEditTrimToBeginningTSMI, nameof(mEditTrimToBeginningTSMI));
         ThrowIfNull(mEditTrimToEndTSMI, nameof(mEditTrimToEndTSMI));
         ThrowIfNull(mEditFindTSMI, nameof(mEditFindTSMI));
         ThrowIfNull(mEditFindNextTSMI, nameof(mEditFindNextTSMI));
         ThrowIfNull(mEditFindPreviousTSMI, nameof(mEditFindPreviousTSMI));
         ThrowIfNull(mEditReplaceTSMI, nameof(mEditReplaceTSMI));
         ThrowIfNull(mEditGoToTSMI, nameof(mEditGoToTSMI));
         ThrowIfNull(mEditWordWrapTSMI, nameof(mEditWordWrapTSMI));
         // Coding — C Family
         ThrowIfNull(mCodingTSMI, nameof(mCodingTSMI));
         ThrowIfNull(mCodingCFamilyTSMI, nameof(mCodingCFamilyTSMI));
         ThrowIfNull(mCSharpCommentAddDoubleTSMI, nameof(mCSharpCommentAddDoubleTSMI));
         ThrowIfNull(mCSharpAddNotImplementedTSMI, nameof(mCSharpAddNotImplementedTSMI));
         ThrowIfNull(mCSharpCommentAddTripleTSMI, nameof(mCSharpCommentAddTripleTSMI));
         ThrowIfNull(mCPlusPlusCommentTSMI, nameof(mCPlusPlusCommentTSMI));
         ThrowIfNull(mCSharpExpressionBodiedMethodTSMI, nameof(mCSharpExpressionBodiedMethodTSMI));
         ThrowIfNull(mCSharpCommentOutTSMI, nameof(mCSharpCommentOutTSMI));
         ThrowIfNull(mCSharpCommentRemoveTSMI, nameof(mCSharpCommentRemoveTSMI));
         ThrowIfNull(mCSharpReverseEqualityTSMI, nameof(mCSharpReverseEqualityTSMI));
         ThrowIfNull(mCSharpWrapTSMI, nameof(mCSharpWrapTSMI));
         // Coding — Basic
         ThrowIfNull(mCodingBasicTSMI, nameof(mCodingBasicTSMI));
         ThrowIfNull(mConvertVBToCSharpCommentTSMI, nameof(mConvertVBToCSharpCommentTSMI));
         ThrowIfNull(mBasicAddSingleQuoteTSMI, nameof(mBasicAddSingleQuoteTSMI));
         ThrowIfNull(mBasicConvertCSharpToVBCommentTSMI, nameof(mBasicConvertCSharpToVBCommentTSMI));
         ThrowIfNull(mBasicReverseEqualityTSMI, nameof(mBasicReverseEqualityTSMI));
         ThrowIfNull(mBasicRemoveLineContinuationTSMI, nameof(mBasicRemoveLineContinuationTSMI));
         ThrowIfNull(mBasicConvertBooleansTSMI, nameof(mBasicConvertBooleansTSMI));
         ThrowIfNull(mBasicConvertNullNothingTSMI, nameof(mBasicConvertNullNothingTSMI));
         ThrowIfNull(mBasicConvertLogicalOperatorsTSMI, nameof(mBasicConvertLogicalOperatorsTSMI));
         // Coding — F#
         ThrowIfNull(mCodingFSharpTSMI, nameof(mCodingFSharpTSMI));
         ThrowIfNull(mFSharpBlockCommentTSMI, nameof(mFSharpBlockCommentTSMI));
         ThrowIfNull(mFSharpAddCommentTSMI, nameof(mFSharpAddCommentTSMI));
         ThrowIfNull(mFSharpAddMutableTSMI, nameof(mFSharpAddMutableTSMI));
         ThrowIfNull(mFSharpAddIgnoreTSMI, nameof(mFSharpAddIgnoreTSMI));
         ThrowIfNull(mFSharpConvertNullNoneTSMI, nameof(mFSharpConvertNullNoneTSMI));
         // Coding — HTML
         ThrowIfNull(mCodingHTMLTSMI, nameof(mCodingHTMLTSMI));
         ThrowIfNull(mHTMLCommentTSMI, nameof(mHTMLCommentTSMI));
         ThrowIfNull(mHTMLBoldTSMI, nameof(mHTMLBoldTSMI));
         ThrowIfNull(mHTMLItalicTSMI, nameof(mHTMLItalicTSMI));
         ThrowIfNull(mHTMLUnderlineTSMI, nameof(mHTMLUnderlineTSMI));
         ThrowIfNull(mHTMLStrikethroughTSMI, nameof(mHTMLStrikethroughTSMI));
         ThrowIfNull(mHTMLBigTSMI, nameof(mHTMLBigTSMI));
         ThrowIfNull(mHTMLBigBigTSMI, nameof(mHTMLBigBigTSMI));
         ThrowIfNull(mHTMLSmallTSMI, nameof(mHTMLSmallTSMI));
         ThrowIfNull(mHTMLSmallSmallTSMI, nameof(mHTMLSmallSmallTSMI));
         ThrowIfNull(mHTMLMarkTSMI, nameof(mHTMLMarkTSMI));
         ThrowIfNull(mHTMLSuperscriptTSMI, nameof(mHTMLSuperscriptTSMI));
         ThrowIfNull(mHTMLSubscriptTSMI, nameof(mHTMLSubscriptTSMI));
         ThrowIfNull(mHTMLCodeTSMI, nameof(mHTMLCodeTSMI));
         ThrowIfNull(mHTMLPreformattedTSMI, nameof(mHTMLPreformattedTSMI));
         ThrowIfNull(mHTMLColorizeTSMI, nameof(mHTMLColorizeTSMI));
         // Coding — CSS
         ThrowIfNull(mCodingCSSTSMI, nameof(mCodingCSSTSMI));
         ThrowIfNull(mCSSBlockCommentTSMI, nameof(mCSSBlockCommentTSMI));
         ThrowIfNull(mCSSCommentRemoveTSMI, nameof(mCSSCommentRemoveTSMI));
         ThrowIfNull(mCSSToggleImportantTSMI, nameof(mCSSToggleImportantTSMI));
         ThrowIfNull(mCSSConvertColorFormatTSMI, nameof(mCSSConvertColorFormatTSMI));
         // Coding — XML
         ThrowIfNull(mCodingXMLTSMI, nameof(mCodingXMLTSMI));
         ThrowIfNull(mXMLCommentTSMI, nameof(mXMLCommentTSMI));
         ThrowIfNull(mXMLRemoveCommentTSMI, nameof(mXMLRemoveCommentTSMI));
         ThrowIfNull(mXMLEscapeEntitiesTSMI, nameof(mXMLEscapeEntitiesTSMI));
         ThrowIfNull(mXMLWrapCDataTSMI, nameof(mXMLWrapCDataTSMI));
         ThrowIfNull(mXMLToggleSelfCloseTSMI, nameof(mXMLToggleSelfCloseTSMI));
         // Coding — JSON
         ThrowIfNull(mCodingJSONTSMI, nameof(mCodingJSONTSMI));
         ThrowIfNull(mJSONAddCommentTSMI, nameof(mJSONAddCommentTSMI));
         ThrowIfNull(mJSONBlockCommentTSMI, nameof(mJSONBlockCommentTSMI));
         ThrowIfNull(mJSONRemoveCommentTSMI, nameof(mJSONRemoveCommentTSMI));
         ThrowIfNull(mJSONToggleQuotesTSMI, nameof(mJSONToggleQuotesTSMI));
         ThrowIfNull(mJSONEscapeStringTSMI, nameof(mJSONEscapeStringTSMI));
         ThrowIfNull(mJSONRemoveTrailingCommasTSMI, nameof(mJSONRemoveTrailingCommasTSMI));
         // Coding — PowerShell
         ThrowIfNull(mCodingPowerShellTSMI, nameof(mCodingPowerShellTSMI));
         ThrowIfNull(mPowerShellAddCommentTSMI, nameof(mPowerShellAddCommentTSMI));
         ThrowIfNull(mPowerShellBlockCommentTSMI, nameof(mPowerShellBlockCommentTSMI));
         ThrowIfNull(mPowerShellRemoveCommentTSMI, nameof(mPowerShellRemoveCommentTSMI));
         ThrowIfNull(mPowerShellToggleBooleanTSMI, nameof(mPowerShellToggleBooleanTSMI));
         ThrowIfNull(mPowerShellToggleQuotesTSMI, nameof(mPowerShellToggleQuotesTSMI));
         // Coding — Batch
         ThrowIfNull(mCodingBatchTSMI, nameof(mCodingBatchTSMI));
         ThrowIfNull(mBatchAddCommentTSMI, nameof(mBatchAddCommentTSMI));
         ThrowIfNull(mBatchAddColonCommentTSMI, nameof(mBatchAddColonCommentTSMI));
         ThrowIfNull(mBatchRemoveCommentTSMI, nameof(mBatchRemoveCommentTSMI));
         ThrowIfNull(mBatchToggleCommentStyleTSMI, nameof(mBatchToggleCommentStyleTSMI));
         // Coding — SQL
         ThrowIfNull(mCodingSQLTSMI, nameof(mCodingSQLTSMI));
         ThrowIfNull(mSQLAddCommentTSMI, nameof(mSQLAddCommentTSMI));
         ThrowIfNull(mSQLBlockCommentTSMI, nameof(mSQLBlockCommentTSMI));
         ThrowIfNull(mSQLRemoveCommentTSMI, nameof(mSQLRemoveCommentTSMI));
         ThrowIfNull(mSQLToggleNullCheckTSMI, nameof(mSQLToggleNullCheckTSMI));
         ThrowIfNull(mSQLToggleBooleanTSMI, nameof(mSQLToggleBooleanTSMI));
         // Coding — Markdown
         ThrowIfNull(mCodingMarkdownTSMI, nameof(mCodingMarkdownTSMI));
         ThrowIfNull(mMarkdownCommentTSMI, nameof(mMarkdownCommentTSMI));
         ThrowIfNull(mMarkdownBoldTSMI, nameof(mMarkdownBoldTSMI));
         ThrowIfNull(mMarkdownItalicTSMI, nameof(mMarkdownItalicTSMI));
         ThrowIfNull(mMarkdownBoldItalicTSMI, nameof(mMarkdownBoldItalicTSMI));
         ThrowIfNull(mMarkdownStrikethroughTSMI, nameof(mMarkdownStrikethroughTSMI));
         ThrowIfNull(mMarkdownCodeTSMI, nameof(mMarkdownCodeTSMI));
         ThrowIfNull(mMarkdownCodeBlockTSMI, nameof(mMarkdownCodeBlockTSMI));
         // Coding — Python
         ThrowIfNull(mCodingPythonTSMI, nameof(mCodingPythonTSMI));
         ThrowIfNull(mPythonAddCommentTSMI, nameof(mPythonAddCommentTSMI));
         ThrowIfNull(mPythonBlockCommentTSMI, nameof(mPythonBlockCommentTSMI));
         ThrowIfNull(mPythonRemoveCommentTSMI, nameof(mPythonRemoveCommentTSMI));
         ThrowIfNull(mPythonToggleBooleanTSMI, nameof(mPythonToggleBooleanTSMI));
         ThrowIfNull(mPythonConvertNullNoneTSMI, nameof(mPythonConvertNullNoneTSMI));
      }

   }
}
