namespace DBCode {
   public sealed partial class MainForm : Form {
      public MainForm() {
         mForm = this;
         Opacity = 0;
         InitializeUIPart1();//efm5 split into parts to help with readability and navigation.
                             //There is some circular dependency between these methods so they can't be fully separated.
                             //efm5 Currently, there is no logic that relies on first launch
         mThisWindow = Handle;
         int wantedWidth = MinimumMainBottomWidth() + 20;
         if (mUiState.mFirstLaunch) {
            mUiState.FormBounds = new Rectangle(new Point(1, 1), new Size(wantedWidth, 300));
            mForm.Bounds = mUiState.FormBounds;
            EnsureWindowFitsMonitor(this);
            CenterFormOnMonitor(this);
            mUiState.FormBounds = mForm.Bounds;
            mUiState.mFirstLaunch = false;
         }
         MinimumSize = new Size(wantedWidth, 150);
         Assembly assembly = Assembly.GetExecutingAssembly();
         FileVersionInfo? fileVersionInfo = FileVersionInfo.GetVersionInfo(assembly.Location);
         if (fileVersionInfo == null)
            mVersionString = "0.0.0.0";
         else {
            if (fileVersionInfo.FileVersion == null)
               mVersionString = "0.0.0.0";
            else {
               mVersionString = fileVersionInfo.FileVersion;
               if (mVersionString == null)
                  mVersionString = "0.0.0.0";
            }
         }
         mVersionLabel?.Text = "v: " + mVersionString;
         mCurrentViewMode = ViewMode.Features;
         mIsTargetingEnabled = false;
         mTargetWindowName = string.Empty;
         mPreMinimalText = Text;
         mPreMinimalControlBox = ControlBox;
         TargetListManager.EnsureDataFiles();
      }

      private void MakeNews() {
         ThrowIfNull(mCurrentTheme, nameof(mCurrentTheme));
         mMenuStrip = new MenuStrip();
         mContextMenuStrip = new ContextMenuStrip();
         mTargetingMenuItem = new ToolStripMenuItem();
         mVisibilityMenuItem = new ToolStripMenuItem();
         mModeMenuItem = new ToolStripMenuItem();
         mLanguageMenuItem = new ToolStripMenuItem();
         mOptionsMenuItem = new ToolStripMenuItem();
         mThemeMenuItem = new ToolStripMenuItem();
         mThemeDesignTSMI = new ToolStripMenuItem();
         mThemePickTSMI = new ToolStripMenuItem();
         mThemeEditTSMI = new ToolStripMenuItem();
         mThemeEditPickTSMI = new ToolStripMenuItem();
         mThemeEditCurrentTSMI = new ToolStripMenuItem();
         mHelpMenuItem = new ToolStripMenuItem();
         mTargetedTSMI = new ToolStripMenuItem();
         mRetargetTSMI = new ToolStripMenuItem();
         mTransparentTSMI = new ToolStripMenuItem();
         mThirtyTSMI = new ToolStripMenuItem();
         mFiftyTSMI = new ToolStripMenuItem();
         mSeventyFiveTSMI = new ToolStripMenuItem();
         mOpaqueTSMI = new ToolStripMenuItem();
         mMinimalTSMI = new ToolStripMenuItem();
         mFeaturesTSMI = new ToolStripMenuItem();
         mPlainTextTSMI = new ToolStripMenuItem();
         mCSharpTSMI = new ToolStripMenuItem();
         mCTSMI = new ToolStripMenuItem();
         mCppTSMI = new ToolStripMenuItem();
         mBasicTSMI = new ToolStripMenuItem();
         mFSharpTSMI = new ToolStripMenuItem();
         mHtmlTSMI = new ToolStripMenuItem();
         mCssTSMI = new ToolStripMenuItem();
         mXmlTSMI = new ToolStripMenuItem();
         mJsonTSMI = new ToolStripMenuItem();
         mPowerShellTSMI = new ToolStripMenuItem();
         mBatchTSMI = new ToolStripMenuItem();
         mSqlTSMI = new ToolStripMenuItem();
         mMarkdownTSMI = new ToolStripMenuItem();
         mPythonTSMI = new ToolStripMenuItem();
         mCurrentThemeIsTSMI = new ToolStripMenuItem();
         mScrollableMainPanel = new ScrollablePanel() {
            Name = "mainPanel",
            AutoScroll = true,
            TabIndex = mTabIndex++,
            BackColor = mCurrentTheme.mInterfaceColors[(int)ColorSwatchUsage.InterfaceBackground]
         };
         mRichTextBox = new RichTextBox();
         mSendAllButton = new Button();
         mPasteSelectedButton = new Button();
         mGetAllButton = new Button();
         mGetSelectedButton = new Button();
         mTargetingLabel = new Label();
         mVersionLabel = new Label();
         mRevertButton = new Button();
         mMainBottomPanel = new BottomPanel(mCurrentTheme, "E&xit");
      }

      private void InitializeUIPart1() {
         mUiState = new UiState();
         mUiState.ReadFromSettings();
         ThemeRegistry.Initialize(); // must precede MakeNews so mCurrentTheme and mThemes are ready
         MakeNews();
         ThrowIfNull(mCurrentTheme, nameof(mCurrentTheme));
         ThrowIfNull(mScrollableMainPanel, nameof(mScrollableMainPanel));
         ThrowIfNull(mRichTextBox, nameof(mRichTextBox));
         ThrowIfNull(mMainBottomPanel, nameof(mMainBottomPanel));
         ThrowIfNull(mMenuStrip, nameof(mMenuStrip));
         ThrowIfNull(mContextMenuStrip, nameof(mContextMenuStrip));
         ThrowIfNull(mTargetingMenuItem, nameof(mTargetingMenuItem));
         ThrowIfNull(mVisibilityMenuItem, nameof(mVisibilityMenuItem));
         ThrowIfNull(mModeMenuItem, nameof(mModeMenuItem));
         ThrowIfNull(mOptionsMenuItem, nameof(mOptionsMenuItem));
         ThrowIfNull(mLanguageMenuItem, nameof(mLanguageMenuItem));
         ThrowIfNull(mThemeMenuItem, nameof(mThemeMenuItem));
         ThrowIfNull(mThemeEditPickTSMI, nameof(mThemeEditPickTSMI));
         ThrowIfNull(mThemeEditCurrentTSMI, nameof(mThemeEditCurrentTSMI));
         ThrowIfNull(mThemeDesignTSMI, nameof(mThemeDesignTSMI));
         ThrowIfNull(mThemeEditTSMI, nameof(mThemeEditTSMI));
         ThrowIfNull(mThemePickTSMI, nameof(mThemePickTSMI));
         ThrowIfNull(mHelpMenuItem, nameof(mHelpMenuItem));
         ThrowIfNull(mTargetedTSMI, nameof(mTargetedTSMI));
         ThrowIfNull(mRetargetTSMI, nameof(mRetargetTSMI));
         ThrowIfNull(mTransparentTSMI, nameof(mTransparentTSMI));
         ThrowIfNull(mThirtyTSMI, nameof(mThirtyTSMI));
         ThrowIfNull(mFiftyTSMI, nameof(mFiftyTSMI));
         ThrowIfNull(mSeventyFiveTSMI, nameof(mSeventyFiveTSMI));
         ThrowIfNull(mOpaqueTSMI, nameof(mOpaqueTSMI));
         ThrowIfNull(mMinimalTSMI, nameof(mMinimalTSMI));
         ThrowIfNull(mFeaturesTSMI, nameof(mFeaturesTSMI));
         ThrowIfNull(mPlainTextTSMI, nameof(mPlainTextTSMI));
         ThrowIfNull(mCSharpTSMI, nameof(mCSharpTSMI));
         ThrowIfNull(mBasicTSMI, nameof(mBasicTSMI));
         ThrowIfNull(mFSharpTSMI, nameof(mFSharpTSMI));
         ThrowIfNull(mHtmlTSMI, nameof(mHtmlTSMI));
         ThrowIfNull(mCssTSMI, nameof(mCssTSMI));
         ThrowIfNull(mXmlTSMI, nameof(mXmlTSMI));
         ThrowIfNull(mJsonTSMI, nameof(mJsonTSMI));
         ThrowIfNull(mPowerShellTSMI, nameof(mPowerShellTSMI));
         ThrowIfNull(mBatchTSMI, nameof(mBatchTSMI));
         ThrowIfNull(mSqlTSMI, nameof(mSqlTSMI));
         ThrowIfNull(mMarkdownTSMI, nameof(mMarkdownTSMI));
         ThrowIfNull(mPythonTSMI, nameof(mPythonTSMI));
         ThrowIfNull(mCurrentThemeIsTSMI, nameof(mCurrentThemeIsTSMI));
         ThrowIfNull(mCTSMI, nameof(mCTSMI));
         ThrowIfNull(mCppTSMI, nameof(mCppTSMI));
         LoadEmbeddedIcons();
         InitializeUIPart2();
         InitializeUIPart3();
         SuspendLayout();
         Controls.Add(mScrollableMainPanel);
         StartPosition = FormStartPosition.Manual;
         ClientSize = new Size(800, 800);
         MinimumSize = new Size(400, 300);
         Text = "DB Code";
         mMenuStrip.Dock = DockStyle.Top;
         mMenuStrip.Name = "menuStrip";
         mMenuStrip.TabIndex = mTabIndex++;
         mMenuStrip.ShowItemToolTips = true;
         mTargetingMenuItem.Name = "targetingMenuItem";
         mTargetingMenuItem.Text = "&Targeting";
         mVisibilityMenuItem.Name = "visibilityMenuItem";
         mVisibilityMenuItem.Text = "&Visibility";
         mModeMenuItem.Name = "modeMenuItem";
         mModeMenuItem.Text = "&Mode";
         mLanguageMenuItem.Name = "languageMenuItem";
         mLanguageMenuItem.Text = "&Language";
         mOptionsMenuItem.Name = "optionsMenuItem";
         mOptionsMenuItem.Text = "&Options";
         mOptionsMenuItem.Click += Options_Click;
         mThemeMenuItem.Name = "themeMenuItem";
         mThemeMenuItem.Text = "&Theme";
         mThemeEditPickTSMI.Name = "themeEditPickTSMI";
         mThemeEditPickTSMI.Text = "Pick To Edit";
         mThemeEditPickTSMI.Click += ThemeEditPick_Click;
         mThemeEditCurrentTSMI.Name = "themeEditCurrentTSMI";
         mThemeEditCurrentTSMI.Text = "Edit Current";
         mThemeEditCurrentTSMI.Click += ThemeEditCurrent_Click;
         mThemeDesignTSMI.Name = "themeDesignTSMI";
         mThemeDesignTSMI.Text = "&Design";
         mThemeDesignTSMI.Click += ThemeDesign_Click;
         mThemeEditTSMI.Name = "themeEditTSMI";
         mThemeEditTSMI.Text = "&Edit";
         mThemePickTSMI.Name = "themePickTSMI";
         mThemePickTSMI.Text = "&Pick";
         mHelpMenuItem.Name = "helpMenuItem";
         mHelpMenuItem.Text = "&Help";
         mHelpMenuItem.Tag = new HelpTag(HelpContext.Main);
         mHelpMenuItem.Click += Help_Click;
         mTargetedTSMI.Name = "targetedTSMI";
         mTargetedTSMI.Text = "&Targeted";
         mTargetedTSMI.CheckOnClick = true;
         mTargetedTSMI.Click += TargetedTSMI_Click;
         mRetargetTSMI.Name = "retargetTSMI";
         mRetargetTSMI.Text = "&Retarget";
         mRetargetTSMI.Click += RetargetTSMI_Click;
         mTransparentTSMI.Name = "transparentTSMI";
         mTransparentTSMI.Text = "&Transparent";
         mTransparentTSMI.Tag = 0.0;
         mTransparentTSMI.Click += VisibilityTSMI_Click;
         mThirtyTSMI.Name = "thirtyTSMI";
         mThirtyTSMI.Text = "&30%";
         mThirtyTSMI.Tag = 0.3;
         mThirtyTSMI.Click += VisibilityTSMI_Click;
         mFiftyTSMI.Name = "fiftyTSMI";
         mFiftyTSMI.Text = "&50%";
         mFiftyTSMI.Tag = 0.5;
         mFiftyTSMI.Click += VisibilityTSMI_Click;
         mSeventyFiveTSMI.Name = "seventyFiveTSMI";
         mSeventyFiveTSMI.Text = "&75%";
         mSeventyFiveTSMI.Tag = 0.75;
         mSeventyFiveTSMI.Click += VisibilityTSMI_Click;
         mOpaqueTSMI.Name = "opaqueTSMI";
         mOpaqueTSMI.Text = "&Opaque";
         mOpaqueTSMI.Tag = 1.0;
         mOpaqueTSMI.Click += VisibilityTSMI_Click;
         mMinimalTSMI.Name = "minimalTSMI";
         mMinimalTSMI.Text = "&Minimal";
         mMinimalTSMI.Click += MinimalTSMI_Click;
         mFeaturesTSMI.Name = "featuresTSMI";
         mFeaturesTSMI.Text = "&Features";
         mFeaturesTSMI.Checked = true;
         mFeaturesTSMI.Click += FeaturesTSMI_Click;
         mPlainTextTSMI.Name = "plaintextTSMI";
         mPlainTextTSMI.Text = "Plain&text";
         mPlainTextTSMI.Tag = LanguageKind.PlainText;
         mPlainTextTSMI.Click += LanguageTSMI_Click;
         mCSharpTSMI.Name = "cSharpTSMI";
         mCSharpTSMI.Text = "CSha&rp";
         mCSharpTSMI.Tag = LanguageKind.CSharp;
         mCSharpTSMI.Click += LanguageTSMI_Click;
         mCTSMI.Name = "cTSMI";
         mCTSMI.Text = "&C";
         mCTSMI.Tag = LanguageKind.C;
         mCTSMI.Click += LanguageTSMI_Click;
         mCppTSMI.Name = "cppTSMI";
         mCppTSMI.Text = "C&pp";
         mCppTSMI.Tag = LanguageKind.Cpp;
         mCppTSMI.Click += LanguageTSMI_Click;
         mBasicTSMI.Name = "basicTSMI";
         mBasicTSMI.Text = "&Basic";
         mBasicTSMI.Tag = LanguageKind.Basic;
         mBasicTSMI.Click += LanguageTSMI_Click;
         mFSharpTSMI.Name = "fSharpTSMI";
         mFSharpTSMI.Text = "&FSharp";
         mFSharpTSMI.Tag = LanguageKind.FSharp;
         mFSharpTSMI.Click += LanguageTSMI_Click;
         mHtmlTSMI.Name = "hTMLTSMI";
         mHtmlTSMI.Text = "&HTML";
         mHtmlTSMI.Tag = LanguageKind.Html;
         mHtmlTSMI.Click += LanguageTSMI_Click;
         mCssTSMI.Name = "cSSTSMI";
         mCssTSMI.Text = "C&SS";
         mCssTSMI.Tag = LanguageKind.Css;
         mCssTSMI.Click += LanguageTSMI_Click;
         mXmlTSMI.Name = "xMLTSMI";
         mXmlTSMI.Text = "&XML";
         mXmlTSMI.Tag = LanguageKind.Xml;
         mXmlTSMI.Click += LanguageTSMI_Click;
         mJsonTSMI.Name = "jSONTSMI";
         mJsonTSMI.Text = "&JSON";
         mJsonTSMI.Tag = LanguageKind.Json;
         mJsonTSMI.Click += LanguageTSMI_Click;
         mPowerShellTSMI.Name = "powerShellTSMI";
         mPowerShellTSMI.Text = "Po&werShell";
         mPowerShellTSMI.Tag = LanguageKind.PowerShell;
         mPowerShellTSMI.Click += LanguageTSMI_Click;
         mBatchTSMI.Name = "batchTSMI";
         mBatchTSMI.Text = "B&atch";
         mBatchTSMI.Tag = LanguageKind.Batch;
         mBatchTSMI.Click += LanguageTSMI_Click;
         mSqlTSMI.Name = "sQLTSMI";
         mSqlTSMI.Text = "S&QL";
         mSqlTSMI.Tag = LanguageKind.Sql;
         mSqlTSMI.Click += LanguageTSMI_Click;
         mMarkdownTSMI.Name = "markdownTSMI";
         mMarkdownTSMI.Text = "&Markdown";
         mMarkdownTSMI.Tag = LanguageKind.Markdown;
         mMarkdownTSMI.Click += LanguageTSMI_Click;
         mPythonTSMI.Name = "pythonTSMI";
         mPythonTSMI.Text = "P&ython";
         mPythonTSMI.Tag = LanguageKind.Python;
         mPythonTSMI.Click += LanguageTSMI_Click;
         mCurrentThemeIsTSMI.Name = "currentThemeIsTSMI";
         mCurrentThemeIsTSMI.Text = mCurrently + mCurrentTheme.mName;
         mThemePickTSMI.DropDownItems.AddRange([mThemeEditPickTSMI, mThemeEditCurrentTSMI]);
         mVisibilityMenuItem.DropDownItems.AddRange([mTransparentTSMI, mThirtyTSMI, mFiftyTSMI,
            mSeventyFiveTSMI, mOpaqueTSMI]);
         mModeMenuItem.DropDownItems.AddRange([mMinimalTSMI, mFeaturesTSMI]);
         mLanguageMenuItem.DropDownItems.AddRange([mPlainTextTSMI, mCSharpTSMI, mCTSMI, mCppTSMI,
            mBasicTSMI, mFSharpTSMI, mHtmlTSMI, mCssTSMI, mXmlTSMI, mJsonTSMI, mPowerShellTSMI, mBatchTSMI,
            mSqlTSMI, mMarkdownTSMI, mPythonTSMI]);
         mMenuStrip.Items.AddRange([mTargetingMenuItem, mVisibilityMenuItem, mModeMenuItem,
            mLanguageMenuItem, mOptionsMenuItem, mThemeMenuItem, mHelpMenuItem]);
         mThemeMenuItem.DropDownItems.AddRange([mCurrentThemeIsTSMI, toolStripSeparator1, mThemePickTSMI,
            mThemeDesignTSMI, mThemeEditTSMI]);
         mTargetingMenuItem.DropDownItems.AddRange([mTargetedTSMI, mRetargetTSMI]);
         Load += MainForm_Load;
         FormClosing += MainForm_FormClosing;
         mHighlighterEngine = new HighlighterEngine(mRichTextBox, mCurrentLanguage);
         mMainBottomPanel.Dock = DockStyle.Bottom;
         mRichTextBox.Dock = DockStyle.Fill;
         mRichTextBox.TextChanged += OnEditorTextChanged;
         InitializeIcon();
         CheckLanguage();
         AdjustForThemeFont(mCurrentTheme.mFonts[(int)FontUsage.Interface]);
         ApplyTheme();
         UpdateTargetingStatusLabel();
         ResumeLayout(false);
         PerformLayout();
      }

      private void InitializeUIPart2() {
         ThrowIfNull(mBasicTSMI, nameof(mBasicTSMI));
         ThrowIfNull(mBatchTSMI, nameof(mBatchTSMI));
         ThrowIfNull(mContextMenuStrip, nameof(mContextMenuStrip));
         ThrowIfNull(mCppTSMI, nameof(mCppTSMI));
         ThrowIfNull(mCSharpTSMI, nameof(mCSharpTSMI));
         ThrowIfNull(mCssTSMI, nameof(mCssTSMI));
         ThrowIfNull(mCTSMI, nameof(mCTSMI));
         ThrowIfNull(mCurrentTheme, nameof(mCurrentTheme));
         ThrowIfNull(mCurrentThemeIsTSMI, nameof(mCurrentThemeIsTSMI));
         ThrowIfNull(mFeaturesTSMI, nameof(mFeaturesTSMI));
         ThrowIfNull(mFiftyTSMI, nameof(mFiftyTSMI));
         ThrowIfNull(mFSharpTSMI, nameof(mFSharpTSMI));
         ThrowIfNull(mHelpMenuItem, nameof(mHelpMenuItem));
         ThrowIfNull(mHtmlTSMI, nameof(mHtmlTSMI));
         ThrowIfNull(mJsonTSMI, nameof(mJsonTSMI));
         ThrowIfNull(mLanguageMenuItem, nameof(mLanguageMenuItem));
         ThrowIfNull(mMainBottomPanel, nameof(mMainBottomPanel));
         ThrowIfNull(mMarkdownTSMI, nameof(mMarkdownTSMI));
         ThrowIfNull(mMenuStrip, nameof(mMenuStrip));
         ThrowIfNull(mMinimalTSMI, nameof(mMinimalTSMI));
         ThrowIfNull(mModeMenuItem, nameof(mModeMenuItem));
         ThrowIfNull(mOpaqueTSMI, nameof(mOpaqueTSMI));
         ThrowIfNull(mOptionsMenuItem, nameof(mOptionsMenuItem));
         ThrowIfNull(mPlainTextTSMI, nameof(mPlainTextTSMI));
         ThrowIfNull(mPowerShellTSMI, nameof(mPowerShellTSMI));
         ThrowIfNull(mPythonTSMI, nameof(mPythonTSMI));
         ThrowIfNull(mRetargetTSMI, nameof(mRetargetTSMI));
         ThrowIfNull(mRichTextBox, nameof(mRichTextBox));
         ThrowIfNull(mScrollableMainPanel, nameof(mScrollableMainPanel));
         ThrowIfNull(mSeventyFiveTSMI, nameof(mSeventyFiveTSMI));
         ThrowIfNull(mSqlTSMI, nameof(mSqlTSMI));
         ThrowIfNull(mTargetedTSMI, nameof(mTargetedTSMI));
         ThrowIfNull(mTargetingMenuItem, nameof(mTargetingMenuItem));
         ThrowIfNull(mThemeDesignTSMI, nameof(mThemeDesignTSMI));
         ThrowIfNull(mThemeEditCurrentTSMI, nameof(mThemeEditCurrentTSMI));
         ThrowIfNull(mThemeEditPickTSMI, nameof(mThemeEditPickTSMI));
         ThrowIfNull(mThemeEditTSMI, nameof(mThemeEditTSMI));
         ThrowIfNull(mThemeMenuItem, nameof(mThemeMenuItem));
         ThrowIfNull(mThemePickTSMI, nameof(mThemePickTSMI));
         ThrowIfNull(mThirtyTSMI, nameof(mThirtyTSMI));
         ThrowIfNull(mTransparentTSMI, nameof(mTransparentTSMI));
         ThrowIfNull(mVisibilityMenuItem, nameof(mVisibilityMenuItem));
         ThrowIfNull(mXmlTSMI, nameof(mXmlTSMI));
         mVisibilityMenuItem.ShortcutKeys = Keys.Control | Keys.G;
         mOptionsMenuItem.ShortcutKeys = Keys.Control | Keys.Shift | Keys.O;
         mThemeEditPickTSMI.ShortcutKeys = Keys.Control | Keys.Shift | Keys.E;
         mThemeEditCurrentTSMI.ShortcutKeys = Keys.Control | Keys.Shift | Keys.C;
         mThemeDesignTSMI.ShortcutKeys = Keys.Control | Keys.Shift | Keys.D;
         mHelpMenuItem.ShortcutKeys = Keys.F1;
         mTargetedTSMI.ShortcutKeys = Keys.Control | Keys.D;
         mRetargetTSMI.ShortcutKeys = Keys.Control | Keys.E;
         mFeaturesTSMI.ShortcutKeys = Keys.Control | Keys.J;
         mFiftyTSMI.ShortcutKeys = Keys.Control | Keys.Q;
         mMinimalTSMI.ShortcutKeys = Keys.Control | Keys.D0;
         mOpaqueTSMI.ShortcutKeys = Keys.Control | Keys.D1;
         mSeventyFiveTSMI.ShortcutKeys = Keys.Control | Keys.D2;
         mThemeEditTSMI.ShortcutKeys = Keys.Control | Keys.D3;
         mThirtyTSMI.ShortcutKeys = Keys.Control | Keys.D4;
         mTransparentTSMI.ShortcutKeys = Keys.Control | Keys.D5;
         mPlainTextTSMI.ShortcutKeys = Keys.Control | Keys.D6;
         mCSharpTSMI.ShortcutKeys = Keys.Control | Keys.D7;
         mCTSMI.ShortcutKeys = Keys.Control | Keys.D8;
         mCppTSMI.ShortcutKeys = Keys.Control | Keys.D9;
         mBasicTSMI.ShortcutKeys = Keys.Control | Keys.Oemtilde;
         mFSharpTSMI.ShortcutKeys = Keys.Control | Keys.OemMinus;
         mHtmlTSMI.ShortcutKeys = Keys.Control | Keys.Oemplus;
         mCssTSMI.ShortcutKeys = Keys.Control | Keys.OemOpenBrackets;
         mXmlTSMI.ShortcutKeys = Keys.Control | Keys.Oem6;
         mJsonTSMI.ShortcutKeys = Keys.Control | Keys.Oem1;
         mPowerShellTSMI.ShortcutKeys = Keys.Control | Keys.Oem7;
         mBatchTSMI.ShortcutKeys = Keys.Control | Keys.Oemcomma;
         mSqlTSMI.ShortcutKeys = Keys.Control | Keys.OemPeriod;
         mMarkdownTSMI.ShortcutKeys = Keys.Control | Keys.Down;
         mPythonTSMI.ShortcutKeys = Keys.Control | Keys.OemQuestion;
         mCurrentThemeIsTSMI.ShortcutKeys = Keys.Control | Keys.OemBackslash;
      }

      private void InitializeUIPart3() {
         ThrowIfNull(mScrollableMainPanel, nameof(mScrollableMainPanel));
         ThrowIfNull(mRichTextBox, nameof(mRichTextBox));
         ThrowIfNull(mSendAllButton, nameof(mSendAllButton));
         ThrowIfNull(mPasteSelectedButton, nameof(mPasteSelectedButton));
         ThrowIfNull(mGetAllButton, nameof(mGetAllButton));
         ThrowIfNull(mGetSelectedButton, nameof(mGetSelectedButton));
         ThrowIfNull(mTargetingLabel, nameof(mTargetingLabel));
         ThrowIfNull(mVersionLabel, nameof(mVersionLabel));
         ThrowIfNull(mRevertButton, nameof(mRevertButton));
         ThrowIfNull(mMainBottomPanel, nameof(mMainBottomPanel));
         mRichTextBox.Multiline = true;
         mRichTextBox.ScrollBars = RichTextBoxScrollBars.Both;
         mRichTextBox.AcceptsTab = true;
         mRichTextBox.WordWrap = false;
         mRichTextBox.Anchor = mAnchorTopLeftBottomRight;
         mRichTextBox.Name = "mainTextBox";
         mRichTextBox.TabIndex = mTabIndex++;
         mSendAllButton.Text = "&Send All";
         mSendAllButton.Name = "sendAllButton";
         mSendAllButton.TabIndex = mTabIndex++;
         mSendAllButton.AutoSize = true;
         mSendAllButton.AutoSizeMode = AutoSizeMode.GrowAndShrink;
         mSendAllButton.Tag = PasteMode.SendAll;
         mSendAllButton.Click += TransMove_Click;
         mPasteSelectedButton.Text = "&Paste Selected";
         mPasteSelectedButton.Name = "pasteSelectedButton";
         mPasteSelectedButton.TabIndex = mTabIndex++;
         mPasteSelectedButton.AutoSize = true;
         mPasteSelectedButton.AutoSizeMode = AutoSizeMode.GrowAndShrink;
         mPasteSelectedButton.Tag = PasteMode.PasteSelected;
         mPasteSelectedButton.Click += TransMove_Click;
         mGetAllButton.Text = "&Get All";
         mGetAllButton.Name = "getAllButton";
         mGetAllButton.TabIndex = mTabIndex++;
         mGetAllButton.AutoSize = true;
         mGetAllButton.AutoSizeMode = AutoSizeMode.GrowAndShrink;
         mGetAllButton.Tag = PasteMode.GetAll;
         mGetAllButton.Click += TransMove_Click;
         mGetSelectedButton.Text = "&Get Selected";
         mGetSelectedButton.Name = "getSelectedButton";
         mGetSelectedButton.TabIndex = mTabIndex++;
         mGetSelectedButton.AutoSize = true;
         mGetSelectedButton.AutoSizeMode = AutoSizeMode.GrowAndShrink;
         mGetSelectedButton.Tag = PasteMode.GetSelected;
         mGetSelectedButton.Click += TransMove_Click;
         mTargetingLabel.Name = "targetingLabel";
         mTargetingLabel.Text = string.Empty;
         mTargetingLabel.ImageAlign = ContentAlignment.MiddleLeft;
         mTargetingLabel.TextAlign = ContentAlignment.MiddleRight;
         mTargetingLabel.TabIndex = mTabIndex++;
         mVersionLabel.Name = "versionLabel";
         mVersionLabel.Text = "v: " + mVersionString;
         mVersionLabel.AutoSize = true;
         mVersionLabel.TextAlign = ContentAlignment.MiddleLeft;
         mVersionLabel.TabIndex = mTabIndex++;
         mRevertButton.Text = "&Revert";
         mRevertButton.Name = "revertButton";
         mRevertButton.TabIndex = mTabIndex++;
         mRevertButton.AutoSize = true;
         mRevertButton.AutoSizeMode = AutoSizeMode.GrowAndShrink;
         mRevertButton.Tag = PasteMode.SendAll;
         mRevertButton.Click += RevertButton_Click;
         mMainBottomPanel.AddLeftControl(mSendAllButton);
         mMainBottomPanel.AddLeftControl(mPasteSelectedButton);
         mMainBottomPanel.AddLeftControl(mGetAllButton);
         mMainBottomPanel.AddLeftControl(mGetSelectedButton);
         mMainBottomPanel.AddLeftControl(mTargetingLabel); // must be last — stretches to fill
         mMainBottomPanel.AddRightControl(mVersionLabel);  // added first = leftmost of right group
         mMainBottomPanel.AddRightControl(mRevertButton);
         ThrowIfNull(mMainBottomPanel.mCancelButton, nameof(mMainBottomPanel.mCancelButton));
         mMainBottomPanel.mCancelButton.Click += ExitButton_Click;
         mScrollableMainPanel.Controls.AddRange([mRichTextBox, mMainBottomPanel, mMenuStrip!]);
         mActiveLayoutable = mMainBottomPanel;
      }
   }
}
