; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "DBCode"
#define MyAppVersion "0.0.0.2"
#define MyAppPublisher "EFM5"
#define MyAppExeName "DBCode.exe"

; Define the source directory macro for easy future updates
#define MySourceDir "E:\DBCode\DBCode\bin\Release\net7.0-windows7.0"

[Setup]
AppId={{E4569FE0-4060-468D-9989-2C93127248DA}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}

; Forces installation strictly into C:\Program Files (x86)\EFM5\DBCode\
DefaultDirName={commonpf32}\{#MyAppPublisher}\{#MyAppName}

UninstallDisplayIcon={app}\{#MyAppExeName}
DisableProgramGroupPage=yes
OutputDir=C:\Users\edgar\Desktop
OutputBaseFilename=DBCodeSetup
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"

[Files]
; Base Application Files
Source: "{#MySourceDir}\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MySourceDir}\shortcuts.tsv"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MySourceDir}\DBCode.deps.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MySourceDir}\DBCode.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MySourceDir}\DBCode.dll.config"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MySourceDir}\DBCode.runtimeconfig.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MySourceDir}\PCRE.NET.dll"; DestDir: "{app}"; Flags: ignoreversion

; FIXED: Preserves the top-level folder names inside the root directory
Source: "{#MySourceDir}\Help\*"; DestDir: "{app}\Help"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#MySourceDir}\runtimes\*"; DestDir: "{app}\runtimes"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
