global using DBCode.Properties;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Drawing;
global using System.IO;
global using System.Linq;
global using System.Net.Http;
global using System.Reflection;
global using System.Runtime.InteropServices.Marshalling;
global using System.Runtime.InteropServices;
global using System.Text;
global using System.Threading.Tasks;
global using System.Threading;
global using System.Windows.Forms;
global using System;
global using static DBCode.Fields;
global using static DBCode.LayoutHelpers;
global using static DBCode.Program.NativeMethods;
global using static DBCode.Program;
global using static DBCode.ZOrderHelper;